# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main_window.ui'
#
# Created: Thu Dec  6 15:54:11 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.resize(1087, 834)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/General/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    MainWindow.setWindowIcon(icon)
    self.centralwidget = QtGui.QWidget(MainWindow)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
    self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
    self.plotTab = QtGui.QTabWidget(self.centralwidget)
    self.plotTab.setObjectName(_fromUtf8("plotTab"))
    self.Overview = QtGui.QWidget()
    self.Overview.setObjectName(_fromUtf8("Overview"))
    self.verticalLayout_13 = QtGui.QVBoxLayout(self.Overview)
    self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
    self.currentChannel = QtGui.QLabel(self.Overview)
    self.currentChannel.setAlignment(QtCore.Qt.AlignCenter)
    self.currentChannel.setObjectName(_fromUtf8("currentChannel"))
    self.verticalLayout_13.addWidget(self.currentChannel)
    self.splitter = QtGui.QSplitter(self.Overview)
    self.splitter.setOrientation(QtCore.Qt.Vertical)
    self.splitter.setObjectName(_fromUtf8("splitter"))
    self.frame = QtGui.QFrame(self.splitter)
    self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
    self.frame.setFrameShadow(QtGui.QFrame.Raised)
    self.frame.setObjectName(_fromUtf8("frame"))
    self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame)
    self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
    self.xy_overview = MPLWidget(self.frame)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.xy_overview.sizePolicy().hasHeightForWidth())
    self.xy_overview.setSizePolicy(sizePolicy)
    self.xy_overview.setMinimumSize(QtCore.QSize(0, 150))
    self.xy_overview.setObjectName(_fromUtf8("xy_overview"))
    self.horizontalLayout_6.addWidget(self.xy_overview)
    self.xtof_overview = MPLWidget(self.frame)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.xtof_overview.sizePolicy().hasHeightForWidth())
    self.xtof_overview.setSizePolicy(sizePolicy)
    self.xtof_overview.setMinimumSize(QtCore.QSize(0, 150))
    self.xtof_overview.setObjectName(_fromUtf8("xtof_overview"))
    self.horizontalLayout_6.addWidget(self.xtof_overview)
    self.widget_3 = QtGui.QWidget(self.splitter)
    self.widget_3.setObjectName(_fromUtf8("widget_3"))
    self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget_3)
    self.verticalLayout_11.setMargin(0)
    self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
    self.groupBox = QtGui.QGroupBox(self.widget_3)
    self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
    self.groupBox.setObjectName(_fromUtf8("groupBox"))
    self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
    self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
    self.label_12 = QtGui.QLabel(self.groupBox)
    self.label_12.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.label_12.setObjectName(_fromUtf8("label_12"))
    self.gridLayout_4.addWidget(self.label_12, 2, 3, 1, 1)
    self.datasetTth = QtGui.QLabel(self.groupBox)
    self.datasetTth.setText(_fromUtf8(""))
    self.datasetTth.setAlignment(QtCore.Qt.AlignCenter)
    self.datasetTth.setMargin(2)
    self.datasetTth.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.datasetTth.setObjectName(_fromUtf8("datasetTth"))
    self.gridLayout_4.addWidget(self.datasetTth, 3, 2, 1, 1)
    self.datasetAi = QtGui.QLabel(self.groupBox)
    self.datasetAi.setText(_fromUtf8(""))
    self.datasetAi.setAlignment(QtCore.Qt.AlignCenter)
    self.datasetAi.setMargin(2)
    self.datasetAi.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.datasetAi.setObjectName(_fromUtf8("datasetAi"))
    self.gridLayout_4.addWidget(self.datasetAi, 3, 4, 1, 1)
    self.label_11 = QtGui.QLabel(self.groupBox)
    self.label_11.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.label_11.setObjectName(_fromUtf8("label_11"))
    self.gridLayout_4.addWidget(self.label_11, 2, 0, 1, 1)
    self.datasetTotCounts = QtGui.QLabel(self.groupBox)
    self.datasetTotCounts.setText(_fromUtf8(""))
    self.datasetTotCounts.setAlignment(QtCore.Qt.AlignCenter)
    self.datasetTotCounts.setMargin(2)
    self.datasetTotCounts.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.datasetTotCounts.setObjectName(_fromUtf8("datasetTotCounts"))
    self.gridLayout_4.addWidget(self.datasetTotCounts, 0, 6, 1, 1)
    self.label_10 = QtGui.QLabel(self.groupBox)
    self.label_10.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.label_10.setObjectName(_fromUtf8("label_10"))
    self.gridLayout_4.addWidget(self.label_10, 0, 5, 1, 1)
    self.datasetROI = QtGui.QLabel(self.groupBox)
    self.datasetROI.setText(_fromUtf8(""))
    self.datasetROI.setAlignment(QtCore.Qt.AlignCenter)
    self.datasetROI.setMargin(2)
    self.datasetROI.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.datasetROI.setObjectName(_fromUtf8("datasetROI"))
    self.gridLayout_4.addWidget(self.datasetROI, 2, 6, 1, 1)
    self.datasetDangle = QtGui.QLabel(self.groupBox)
    self.datasetDangle.setText(_fromUtf8(""))
    self.datasetDangle.setAlignment(QtCore.Qt.AlignCenter)
    self.datasetDangle.setMargin(2)
    self.datasetDangle.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.datasetDangle.setObjectName(_fromUtf8("datasetDangle"))
    self.gridLayout_4.addWidget(self.datasetDangle, 2, 2, 1, 1)
    self.datasetPCharge = QtGui.QLabel(self.groupBox)
    self.datasetPCharge.setText(_fromUtf8(""))
    self.datasetPCharge.setAlignment(QtCore.Qt.AlignCenter)
    self.datasetPCharge.setMargin(2)
    self.datasetPCharge.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.datasetPCharge.setObjectName(_fromUtf8("datasetPCharge"))
    self.gridLayout_4.addWidget(self.datasetPCharge, 0, 4, 1, 1)
    self.label_8 = QtGui.QLabel(self.groupBox)
    self.label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.label_8.setObjectName(_fromUtf8("label_8"))
    self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
    self.label_14 = QtGui.QLabel(self.groupBox)
    self.label_14.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.label_14.setObjectName(_fromUtf8("label_14"))
    self.gridLayout_4.addWidget(self.label_14, 2, 5, 1, 1)
    self.datasetName = QtGui.QLabel(self.groupBox)
    self.datasetName.setText(_fromUtf8(""))
    self.datasetName.setAlignment(QtCore.Qt.AlignCenter)
    self.datasetName.setMargin(2)
    self.datasetName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.datasetName.setObjectName(_fromUtf8("datasetName"))
    self.gridLayout_4.addWidget(self.datasetName, 0, 2, 1, 1)
    self.datasetSangle = QtGui.QLabel(self.groupBox)
    self.datasetSangle.setText(_fromUtf8(""))
    self.datasetSangle.setAlignment(QtCore.Qt.AlignCenter)
    self.datasetSangle.setMargin(2)
    self.datasetSangle.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.datasetSangle.setObjectName(_fromUtf8("datasetSangle"))
    self.gridLayout_4.addWidget(self.datasetSangle, 2, 4, 1, 1)
    self.label_9 = QtGui.QLabel(self.groupBox)
    self.label_9.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.label_9.setObjectName(_fromUtf8("label_9"))
    self.gridLayout_4.addWidget(self.label_9, 0, 3, 1, 1)
    self.label_13 = QtGui.QLabel(self.groupBox)
    self.label_13.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.label_13.setObjectName(_fromUtf8("label_13"))
    self.gridLayout_4.addWidget(self.label_13, 3, 3, 1, 1)
    self.label_15 = QtGui.QLabel(self.groupBox)
    self.label_15.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.label_15.setObjectName(_fromUtf8("label_15"))
    self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
    self.label_17 = QtGui.QLabel(self.groupBox)
    self.label_17.setObjectName(_fromUtf8("label_17"))
    self.gridLayout_4.addWidget(self.label_17, 3, 5, 1, 1)
    self.datasetDirectPixel = QtGui.QLabel(self.groupBox)
    self.datasetDirectPixel.setText(_fromUtf8(""))
    self.datasetDirectPixel.setObjectName(_fromUtf8("datasetDirectPixel"))
    self.gridLayout_4.addWidget(self.datasetDirectPixel, 3, 6, 1, 1)
    self.verticalLayout_11.addWidget(self.groupBox)
    self.groupBox_2 = QtGui.QGroupBox(self.widget_3)
    self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
    self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_2)
    self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
    self.horizontalLayout_7 = QtGui.QHBoxLayout()
    self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
    self.label_7 = QtGui.QLabel(self.groupBox_2)
    self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_7.setObjectName(_fromUtf8("label_7"))
    self.horizontalLayout_7.addWidget(self.label_7)
    self.normalizationLabel = QtGui.QLabel(self.groupBox_2)
    self.normalizationLabel.setAlignment(QtCore.Qt.AlignCenter)
    self.normalizationLabel.setObjectName(_fromUtf8("normalizationLabel"))
    self.horizontalLayout_7.addWidget(self.normalizationLabel)
    self.selectedChannel = QtGui.QComboBox(self.groupBox_2)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.selectedChannel.sizePolicy().hasHeightForWidth())
    self.selectedChannel.setSizePolicy(sizePolicy)
    self.selectedChannel.setObjectName(_fromUtf8("selectedChannel"))
    self.selectedChannel.addItem(_fromUtf8(""))
    self.selectedChannel.addItem(_fromUtf8(""))
    self.selectedChannel.addItem(_fromUtf8(""))
    self.selectedChannel.addItem(_fromUtf8(""))
    self.horizontalLayout_7.addWidget(self.selectedChannel)
    self.verticalLayout_12.addLayout(self.horizontalLayout_7)
    self.reductionTable = QtGui.QTableWidget(self.groupBox_2)
    self.reductionTable.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
    self.reductionTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
    self.reductionTable.setWordWrap(False)
    self.reductionTable.setRowCount(0)
    self.reductionTable.setObjectName(_fromUtf8("reductionTable"))
    self.reductionTable.setColumnCount(13)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(0, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(1, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(2, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(3, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(4, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(5, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(6, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(7, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(8, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(9, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(10, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(11, item)
    item = QtGui.QTableWidgetItem()
    self.reductionTable.setHorizontalHeaderItem(12, item)
    self.reductionTable.horizontalHeader().setVisible(True)
    self.reductionTable.horizontalHeader().setDefaultSectionSize(50)
    self.reductionTable.horizontalHeader().setMinimumSectionSize(25)
    self.reductionTable.verticalHeader().setVisible(False)
    self.reductionTable.verticalHeader().setDefaultSectionSize(20)
    self.verticalLayout_12.addWidget(self.reductionTable)
    self.horizontalLayout_5 = QtGui.QHBoxLayout()
    self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
    self.reduceButton = QtGui.QPushButton(self.groupBox_2)
    self.reduceButton.setObjectName(_fromUtf8("reduceButton"))
    self.horizontalLayout_5.addWidget(self.reduceButton)
    self.verticalLayout_12.addLayout(self.horizontalLayout_5)
    self.verticalLayout_11.addWidget(self.groupBox_2)
    self.verticalLayout_13.addWidget(self.splitter)
    self.plotTab.addTab(self.Overview, _fromUtf8(""))
    self.tab = QtGui.QWidget()
    self.tab.setObjectName(_fromUtf8("tab"))
    self.gridLayout = QtGui.QGridLayout(self.tab)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.frame_xy_pp = PersistentFrame(self.tab)
    self.frame_xy_pp.setFrameShape(QtGui.QFrame.StyledPanel)
    self.frame_xy_pp.setFrameShadow(QtGui.QFrame.Raised)
    self.frame_xy_pp.setObjectName(_fromUtf8("frame_xy_pp"))
    self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_xy_pp)
    self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
    self.xy_pp = MPLWidget(self.frame_xy_pp)
    self.xy_pp.setMinimumSize(QtCore.QSize(150, 150))
    self.xy_pp.setObjectName(_fromUtf8("xy_pp"))
    self.verticalLayout_3.addWidget(self.xy_pp)
    self.gridLayout.addWidget(self.frame_xy_pp, 0, 0, 1, 1)
    self.frame_xy_mm = PersistentFrame(self.tab)
    self.frame_xy_mm.setFrameShape(QtGui.QFrame.StyledPanel)
    self.frame_xy_mm.setFrameShadow(QtGui.QFrame.Raised)
    self.frame_xy_mm.setObjectName(_fromUtf8("frame_xy_mm"))
    self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_xy_mm)
    self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
    self.xy_mm = MPLWidget(self.frame_xy_mm)
    self.xy_mm.setMinimumSize(QtCore.QSize(150, 150))
    self.xy_mm.setObjectName(_fromUtf8("xy_mm"))
    self.verticalLayout_4.addWidget(self.xy_mm)
    self.gridLayout.addWidget(self.frame_xy_mm, 0, 1, 1, 1)
    self.frame_xy_sf = PersistentFrame(self.tab)
    self.frame_xy_sf.setFrameShape(QtGui.QFrame.StyledPanel)
    self.frame_xy_sf.setFrameShadow(QtGui.QFrame.Raised)
    self.frame_xy_sf.setObjectName(_fromUtf8("frame_xy_sf"))
    self.horizontalLayout = QtGui.QHBoxLayout(self.frame_xy_sf)
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.xy_pm = MPLWidget(self.frame_xy_sf)
    self.xy_pm.setMinimumSize(QtCore.QSize(150, 150))
    self.xy_pm.setObjectName(_fromUtf8("xy_pm"))
    self.horizontalLayout.addWidget(self.xy_pm)
    self.xy_mp = MPLWidget(self.frame_xy_sf)
    self.xy_mp.setMinimumSize(QtCore.QSize(150, 105))
    self.xy_mp.setObjectName(_fromUtf8("xy_mp"))
    self.horizontalLayout.addWidget(self.xy_mp)
    self.gridLayout.addWidget(self.frame_xy_sf, 1, 0, 1, 2)
    self.plotTab.addTab(self.tab, _fromUtf8(""))
    self.tab_2 = QtGui.QWidget()
    self.tab_2.setObjectName(_fromUtf8("tab_2"))
    self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
    self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
    self.frame_xtof_pp = PersistentFrame(self.tab_2)
    self.frame_xtof_pp.setFrameShape(QtGui.QFrame.StyledPanel)
    self.frame_xtof_pp.setFrameShadow(QtGui.QFrame.Raised)
    self.frame_xtof_pp.setObjectName(_fromUtf8("frame_xtof_pp"))
    self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_xtof_pp)
    self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
    self.xtof_pp = MPLWidget(self.frame_xtof_pp)
    self.xtof_pp.setObjectName(_fromUtf8("xtof_pp"))
    self.verticalLayout_7.addWidget(self.xtof_pp)
    self.gridLayout_2.addWidget(self.frame_xtof_pp, 0, 0, 1, 1)
    self.frame_xtof_mm = PersistentFrame(self.tab_2)
    self.frame_xtof_mm.setFrameShape(QtGui.QFrame.StyledPanel)
    self.frame_xtof_mm.setFrameShadow(QtGui.QFrame.Raised)
    self.frame_xtof_mm.setObjectName(_fromUtf8("frame_xtof_mm"))
    self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_xtof_mm)
    self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
    self.xtof_mm = MPLWidget(self.frame_xtof_mm)
    self.xtof_mm.setObjectName(_fromUtf8("xtof_mm"))
    self.verticalLayout_8.addWidget(self.xtof_mm)
    self.gridLayout_2.addWidget(self.frame_xtof_mm, 0, 1, 1, 1)
    self.frame_xtof_sf = PersistentFrame(self.tab_2)
    self.frame_xtof_sf.setFrameShape(QtGui.QFrame.StyledPanel)
    self.frame_xtof_sf.setFrameShadow(QtGui.QFrame.Raised)
    self.frame_xtof_sf.setObjectName(_fromUtf8("frame_xtof_sf"))
    self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_xtof_sf)
    self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
    self.xtof_pm = MPLWidget(self.frame_xtof_sf)
    self.xtof_pm.setObjectName(_fromUtf8("xtof_pm"))
    self.horizontalLayout_2.addWidget(self.xtof_pm)
    self.xtof_mp = MPLWidget(self.frame_xtof_sf)
    self.xtof_mp.setObjectName(_fromUtf8("xtof_mp"))
    self.horizontalLayout_2.addWidget(self.xtof_mp)
    self.gridLayout_2.addWidget(self.frame_xtof_sf, 1, 0, 1, 2)
    self.plotTab.addTab(self.tab_2, _fromUtf8(""))
    self.tab_3 = QtGui.QWidget()
    self.tab_3.setObjectName(_fromUtf8("tab_3"))
    self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab_3)
    self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
    self.offspec = MPLWidget(self.tab_3)
    self.offspec.setObjectName(_fromUtf8("offspec"))
    self.verticalLayout_14.addWidget(self.offspec)
    self.plotTab.addTab(self.tab_3, _fromUtf8(""))
    self.verticalLayout_2.addWidget(self.plotTab)
    MainWindow.setCentralWidget(self.centralwidget)
    self.menubar = QtGui.QMenuBar(MainWindow)
    self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 21))
    self.menubar.setObjectName(_fromUtf8("menubar"))
    self.menuFile = QtGui.QMenu(self.menubar)
    self.menuFile.setObjectName(_fromUtf8("menuFile"))
    self.menuReduce = QtGui.QMenu(self.menubar)
    self.menuReduce.setObjectName(_fromUtf8("menuReduce"))
    MainWindow.setMenuBar(self.menubar)
    self.statusbar = QtGui.QStatusBar(MainWindow)
    self.statusbar.setObjectName(_fromUtf8("statusbar"))
    MainWindow.setStatusBar(self.statusbar)
    self.dockWidget = QtGui.QDockWidget(MainWindow)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
    self.dockWidget.setSizePolicy(sizePolicy)
    self.dockWidget.setMinimumSize(QtCore.QSize(189, 162))
    self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
    self.dockWidgetContents = QtGui.QWidget()
    self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
    self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
    self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
    self.file_list = QtGui.QListWidget(self.dockWidgetContents)
    self.file_list.setObjectName(_fromUtf8("file_list"))
    self.verticalLayout.addWidget(self.file_list)
    self.dockWidget.setWidget(self.dockWidgetContents)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
    self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
    self.dockWidget_2.setSizePolicy(sizePolicy)
    self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
    self.dockWidgetContents_2 = QtGui.QWidget()
    self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
    self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
    self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
    self.show_colorbars = QtGui.QCheckBox(self.dockWidgetContents_2)
    self.show_colorbars.setObjectName(_fromUtf8("show_colorbars"))
    self.verticalLayout_5.addWidget(self.show_colorbars)
    self.hide_plots = QtGui.QCheckBox(self.dockWidgetContents_2)
    self.hide_plots.setObjectName(_fromUtf8("hide_plots"))
    self.verticalLayout_5.addWidget(self.hide_plots)
    self.normalizeXTof = QtGui.QCheckBox(self.dockWidgetContents_2)
    self.normalizeXTof.setObjectName(_fromUtf8("normalizeXTof"))
    self.verticalLayout_5.addWidget(self.normalizeXTof)
    self.color_selector = QtGui.QComboBox(self.dockWidgetContents_2)
    self.color_selector.setObjectName(_fromUtf8("color_selector"))
    self.color_selector.addItem(_fromUtf8(""))
    self.color_selector.addItem(_fromUtf8(""))
    self.color_selector.addItem(_fromUtf8(""))
    self.color_selector.addItem(_fromUtf8(""))
    self.color_selector.addItem(_fromUtf8(""))
    self.color_selector.addItem(_fromUtf8(""))
    self.verticalLayout_5.addWidget(self.color_selector)
    self.dockWidget_2.setWidget(self.dockWidgetContents_2)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
    self.dockWidget_3 = QtGui.QDockWidget(MainWindow)
    self.dockWidget_3.setObjectName(_fromUtf8("dockWidget_3"))
    self.dockWidgetContents_3 = QtGui.QWidget()
    self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
    self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
    self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
    self.y_project = MPLWidget(self.dockWidgetContents_3)
    self.y_project.setMinimumSize(QtCore.QSize(150, 150))
    self.y_project.setObjectName(_fromUtf8("y_project"))
    self.verticalLayout_6.addWidget(self.y_project)
    self.dockWidget_3.setWidget(self.dockWidgetContents_3)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)
    self.dockWidget_4 = QtGui.QDockWidget(MainWindow)
    self.dockWidget_4.setObjectName(_fromUtf8("dockWidget_4"))
    self.dockWidgetContents_5 = QtGui.QWidget()
    self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
    self.verticalLayout_9 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
    self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
    self.horizontalLayout_4 = QtGui.QHBoxLayout()
    self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
    self.xprojUseQuantiles = QtGui.QCheckBox(self.dockWidgetContents_5)
    self.xprojUseQuantiles.setObjectName(_fromUtf8("xprojUseQuantiles"))
    self.horizontalLayout_4.addWidget(self.xprojUseQuantiles)
    self.xprojQuantiles = QtGui.QDoubleSpinBox(self.dockWidgetContents_5)
    self.xprojQuantiles.setMinimum(30.0)
    self.xprojQuantiles.setSingleStep(5.0)
    self.xprojQuantiles.setProperty("value", 50.0)
    self.xprojQuantiles.setObjectName(_fromUtf8("xprojQuantiles"))
    self.horizontalLayout_4.addWidget(self.xprojQuantiles)
    self.label_16 = QtGui.QLabel(self.dockWidgetContents_5)
    self.label_16.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    self.label_16.setObjectName(_fromUtf8("label_16"))
    self.horizontalLayout_4.addWidget(self.label_16)
    self.verticalLayout_9.addLayout(self.horizontalLayout_4)
    self.x_project = MPLWidget(self.dockWidgetContents_5)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.x_project.sizePolicy().hasHeightForWidth())
    self.x_project.setSizePolicy(sizePolicy)
    self.x_project.setMinimumSize(QtCore.QSize(150, 150))
    self.x_project.setObjectName(_fromUtf8("x_project"))
    self.verticalLayout_9.addWidget(self.x_project)
    self.dockWidget_4.setWidget(self.dockWidgetContents_5)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)
    self.dockWidget_5 = QtGui.QDockWidget(MainWindow)
    self.dockWidget_5.setObjectName(_fromUtf8("dockWidget_5"))
    self.dockWidgetContents_6 = QtGui.QWidget()
    self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
    self.verticalLayout_10 = QtGui.QVBoxLayout(self.dockWidgetContents_6)
    self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
    self.refl = MPLWidget(self.dockWidgetContents_6)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.refl.sizePolicy().hasHeightForWidth())
    self.refl.setSizePolicy(sizePolicy)
    self.refl.setMinimumSize(QtCore.QSize(150, 150))
    self.refl.setObjectName(_fromUtf8("refl"))
    self.verticalLayout_10.addWidget(self.refl)
    self.dockWidget_5.setWidget(self.dockWidgetContents_6)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_5)
    self.dockWidget_6 = QtGui.QDockWidget(MainWindow)
    self.dockWidget_6.setObjectName(_fromUtf8("dockWidget_6"))
    self.dockWidgetContents_4 = QtGui.QWidget()
    self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
    self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_4)
    self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
    self.gridLayout_3.setVerticalSpacing(0)
    self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
    self.label_4 = QtGui.QLabel(self.dockWidgetContents_4)
    self.label_4.setObjectName(_fromUtf8("label_4"))
    self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
    self.label_3 = QtGui.QLabel(self.dockWidgetContents_4)
    self.label_3.setObjectName(_fromUtf8("label_3"))
    self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
    self.label_5 = QtGui.QLabel(self.dockWidgetContents_4)
    self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_5.setObjectName(_fromUtf8("label_5"))
    self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 2)
    self.refYWidth = QtGui.QDoubleSpinBox(self.dockWidgetContents_4)
    self.refYWidth.setDecimals(1)
    self.refYWidth.setMinimum(1.0)
    self.refYWidth.setMaximum(400.0)
    self.refYWidth.setProperty("value", 6.0)
    self.refYWidth.setObjectName(_fromUtf8("refYWidth"))
    self.gridLayout_3.addWidget(self.refYWidth, 2, 2, 1, 1)
    self.refXWidth = QtGui.QDoubleSpinBox(self.dockWidgetContents_4)
    self.refXWidth.setDecimals(1)
    self.refXWidth.setMinimum(1.0)
    self.refXWidth.setProperty("value", 6.0)
    self.refXWidth.setObjectName(_fromUtf8("refXWidth"))
    self.gridLayout_3.addWidget(self.refXWidth, 3, 2, 1, 1)
    self.refScale = QtGui.QDoubleSpinBox(self.dockWidgetContents_4)
    self.refScale.setDecimals(2)
    self.refScale.setMinimum(-20.0)
    self.refScale.setMaximum(20.0)
    self.refScale.setSingleStep(0.02)
    self.refScale.setProperty("value", 0.0)
    self.refScale.setObjectName(_fromUtf8("refScale"))
    self.gridLayout_3.addWidget(self.refScale, 5, 2, 1, 1)
    self.label_2 = QtGui.QLabel(self.dockWidgetContents_4)
    self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
    self.label_2.setObjectName(_fromUtf8("label_2"))
    self.gridLayout_3.addWidget(self.label_2, 1, 2, 1, 1)
    self.label = QtGui.QLabel(self.dockWidgetContents_4)
    self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
    self.label.setObjectName(_fromUtf8("label"))
    self.gridLayout_3.addWidget(self.label, 1, 1, 1, 1)
    self.refXPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_4)
    self.refXPos.setDecimals(1)
    self.refXPos.setMaximum(400.0)
    self.refXPos.setObjectName(_fromUtf8("refXPos"))
    self.gridLayout_3.addWidget(self.refXPos, 3, 1, 1, 1)
    self.bgCenter = QtGui.QDoubleSpinBox(self.dockWidgetContents_4)
    self.bgCenter.setDecimals(1)
    self.bgCenter.setMaximum(400.0)
    self.bgCenter.setObjectName(_fromUtf8("bgCenter"))
    self.gridLayout_3.addWidget(self.bgCenter, 4, 1, 1, 1)
    spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
    self.gridLayout_3.addItem(spacerItem, 7, 1, 1, 1)
    self.bgWidth = QtGui.QDoubleSpinBox(self.dockWidgetContents_4)
    self.bgWidth.setDecimals(1)
    self.bgWidth.setMaximum(400.0)
    self.bgWidth.setObjectName(_fromUtf8("bgWidth"))
    self.gridLayout_3.addWidget(self.bgWidth, 4, 2, 1, 1)
    self.label_6 = QtGui.QLabel(self.dockWidgetContents_4)
    self.label_6.setObjectName(_fromUtf8("label_6"))
    self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
    spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
    self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
    self.label_20 = QtGui.QLabel(self.dockWidgetContents_4)
    self.label_20.setObjectName(_fromUtf8("label_20"))
    self.gridLayout_3.addWidget(self.label_20, 6, 0, 1, 1)
    self.rangeStart = QtGui.QSpinBox(self.dockWidgetContents_4)
    self.rangeStart.setMaximum(30)
    self.rangeStart.setObjectName(_fromUtf8("rangeStart"))
    self.gridLayout_3.addWidget(self.rangeStart, 6, 1, 1, 1)
    self.rangeEnd = QtGui.QSpinBox(self.dockWidgetContents_4)
    self.rangeEnd.setMaximum(30)
    self.rangeEnd.setProperty("value", 30)
    self.rangeEnd.setObjectName(_fromUtf8("rangeEnd"))
    self.gridLayout_3.addWidget(self.rangeEnd, 6, 2, 1, 1)
    self.refYPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_4)
    self.refYPos.setDecimals(1)
    self.refYPos.setMaximum(400.0)
    self.refYPos.setObjectName(_fromUtf8("refYPos"))
    self.gridLayout_3.addWidget(self.refYPos, 2, 1, 1, 1)
    self.dockWidget_6.setWidget(self.dockWidgetContents_4)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_6)
    self.toolBar = QtGui.QToolBar(MainWindow)
    self.toolBar.setObjectName(_fromUtf8("toolBar"))
    MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
    self.dockWidget_7 = QtGui.QDockWidget(MainWindow)
    self.dockWidget_7.setObjectName(_fromUtf8("dockWidget_7"))
    self.dockWidgetContents_7 = QtGui.QWidget()
    self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
    self.formLayout = QtGui.QFormLayout(self.dockWidgetContents_7)
    self.formLayout.setObjectName(_fromUtf8("formLayout"))
    self.label_18 = QtGui.QLabel(self.dockWidgetContents_7)
    self.label_18.setObjectName(_fromUtf8("label_18"))
    self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
    self.directPixelOverwrite = QtGui.QDoubleSpinBox(self.dockWidgetContents_7)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.directPixelOverwrite.sizePolicy().hasHeightForWidth())
    self.directPixelOverwrite.setSizePolicy(sizePolicy)
    self.directPixelOverwrite.setDecimals(1)
    self.directPixelOverwrite.setMinimum(-1.0)
    self.directPixelOverwrite.setMaximum(304.0)
    self.directPixelOverwrite.setSingleStep(1.0)
    self.directPixelOverwrite.setProperty("value", -1.0)
    self.directPixelOverwrite.setObjectName(_fromUtf8("directPixelOverwrite"))
    self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.directPixelOverwrite)
    self.label_19 = QtGui.QLabel(self.dockWidgetContents_7)
    self.label_19.setObjectName(_fromUtf8("label_19"))
    self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
    self.dangle0Overwrite = QtGui.QLineEdit(self.dockWidgetContents_7)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.dangle0Overwrite.sizePolicy().hasHeightForWidth())
    self.dangle0Overwrite.setSizePolicy(sizePolicy)
    self.dangle0Overwrite.setObjectName(_fromUtf8("dangle0Overwrite"))
    self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dangle0Overwrite)
    self.fanReflectivity = QtGui.QCheckBox(self.dockWidgetContents_7)
    self.fanReflectivity.setObjectName(_fromUtf8("fanReflectivity"))
    self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.fanReflectivity)
    self.dockWidget_7.setWidget(self.dockWidgetContents_7)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_7)
    self.actionOpen = QtGui.QAction(MainWindow)
    icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
    self.actionOpen.setIcon(icon)
    self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
    self.actionNext_File = QtGui.QAction(MainWindow)
    icon = QtGui.QIcon.fromTheme(_fromUtf8("go-next"))
    self.actionNext_File.setIcon(icon)
    self.actionNext_File.setObjectName(_fromUtf8("actionNext_File"))
    self.actionPrevious_File = QtGui.QAction(MainWindow)
    icon = QtGui.QIcon.fromTheme(_fromUtf8("go-previous"))
    self.actionPrevious_File.setIcon(icon)
    self.actionPrevious_File.setObjectName(_fromUtf8("actionPrevious_File"))
    self.actionNorm = QtGui.QAction(MainWindow)
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/General/extractNormalization.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionNorm.setIcon(icon1)
    self.actionNorm.setObjectName(_fromUtf8("actionNorm"))
    self.actionAddPlot = QtGui.QAction(MainWindow)
    icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
    self.actionAddPlot.setIcon(icon)
    self.actionAddPlot.setObjectName(_fromUtf8("actionAddPlot"))
    self.actionClear = QtGui.QAction(MainWindow)
    icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-delete"))
    self.actionClear.setIcon(icon)
    self.actionClear.setObjectName(_fromUtf8("actionClear"))
    self.actionAdjust_Dirct_Beam = QtGui.QAction(MainWindow)
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/General/tthZero.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionAdjust_Dirct_Beam.setIcon(icon2)
    self.actionAdjust_Dirct_Beam.setObjectName(_fromUtf8("actionAdjust_Dirct_Beam"))
    self.actionNormalizeScaling = QtGui.QAction(MainWindow)
    icon3 = QtGui.QIcon()
    icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/General/totalReflection.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionNormalizeScaling.setIcon(icon3)
    self.actionNormalizeScaling.setObjectName(_fromUtf8("actionNormalizeScaling"))
    self.actionRemove = QtGui.QAction(MainWindow)
    icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
    self.actionRemove.setIcon(icon)
    self.actionRemove.setObjectName(_fromUtf8("actionRemove"))
    self.menuFile.addAction(self.actionOpen)
    self.menuFile.addAction(self.actionNext_File)
    self.menuFile.addAction(self.actionPrevious_File)
    self.menuReduce.addAction(self.actionNorm)
    self.menuReduce.addAction(self.actionNormalizeScaling)
    self.menuReduce.addSeparator()
    self.menuReduce.addAction(self.actionAddPlot)
    self.menuReduce.addAction(self.actionRemove)
    self.menuReduce.addAction(self.actionClear)
    self.menuReduce.addSeparator()
    self.menuReduce.addAction(self.actionAdjust_Dirct_Beam)
    self.menubar.addAction(self.menuFile.menuAction())
    self.menubar.addAction(self.menuReduce.menuAction())
    self.toolBar.addAction(self.actionOpen)
    self.toolBar.addAction(self.actionPrevious_File)
    self.toolBar.addAction(self.actionNext_File)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.actionNorm)
    self.toolBar.addAction(self.actionNormalizeScaling)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.actionAddPlot)
    self.toolBar.addAction(self.actionRemove)
    self.toolBar.addAction(self.actionClear)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.actionAdjust_Dirct_Beam)

    self.retranslateUi(MainWindow)
    self.plotTab.setCurrentIndex(0)
    QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.fileOpenDialog)
    QtCore.QObject.connect(self.plotTab, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.plotActiveTab)
    QtCore.QObject.connect(self.file_list, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.fileOpenList)
    QtCore.QObject.connect(self.show_colorbars, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.toggleColorbars)
    QtCore.QObject.connect(self.hide_plots, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.toggleHide)
    QtCore.QObject.connect(self.color_selector, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.toggleColorbars)
    QtCore.QObject.connect(self.refScale, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.plot_refl)
    QtCore.QObject.connect(self.refYPos, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.changeRegionValues)
    QtCore.QObject.connect(self.refYWidth, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.changeRegionValues)
    QtCore.QObject.connect(self.refXPos, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.changeRegionValues)
    QtCore.QObject.connect(self.refXWidth, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.changeRegionValues)
    QtCore.QObject.connect(self.bgCenter, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.changeRegionValues)
    QtCore.QObject.connect(self.bgWidth, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.changeRegionValues)
    QtCore.QObject.connect(self.xprojQuantiles, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.replotProjections)
    QtCore.QObject.connect(self.xprojUseQuantiles, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.replotProjections)
    QtCore.QObject.connect(self.actionNext_File, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.nextFile)
    QtCore.QObject.connect(self.actionPrevious_File, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.prevFile)
    QtCore.QObject.connect(self.actionNorm, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.setNorm)
    QtCore.QObject.connect(self.actionAddPlot, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.addRefList)
    QtCore.QObject.connect(self.actionClear, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.clearRefList)
    QtCore.QObject.connect(self.reduceButton, QtCore.SIGNAL(_fromUtf8("pressed()")), MainWindow.reduceDatasets)
    QtCore.QObject.connect(self.actionAdjust_Dirct_Beam, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.overwriteDirectBeam)
    QtCore.QObject.connect(self.directPixelOverwrite, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.overwriteChanged)
    QtCore.QObject.connect(self.dangle0Overwrite, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.overwriteChanged)
    QtCore.QObject.connect(self.actionNormalizeScaling, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.normalizeTotalReflection)
    QtCore.QObject.connect(self.rangeStart, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.plot_refl)
    QtCore.QObject.connect(self.rangeEnd, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.plot_refl)
    QtCore.QObject.connect(self.reductionTable, QtCore.SIGNAL(_fromUtf8("itemChanged(QTableWidgetItem*)")), MainWindow.reductionTableChanged)
    QtCore.QObject.connect(self.selectedChannel, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.changeActiveChannel)
    QtCore.QObject.connect(self.fanReflectivity, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.plot_refl)
    QtCore.QObject.connect(self.actionRemove, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.removeRefList)
    QtCore.QObject.connect(self.normalizeXTof, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.toggleColorbars)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QuickNXS", None, QtGui.QApplication.UnicodeUTF8))
    self.currentChannel.setText(QtGui.QApplication.translate("MainWindow", "Current Channel: +", None, QtGui.QApplication.UnicodeUTF8))
    self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Active Dataset Information", None, QtGui.QApplication.UnicodeUTF8))
    self.label_12.setText(QtGui.QApplication.translate("MainWindow", "SANGLE", None, QtGui.QApplication.UnicodeUTF8))
    self.label_11.setText(QtGui.QApplication.translate("MainWindow", "DANGLE", None, QtGui.QApplication.UnicodeUTF8))
    self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Total Counts", None, QtGui.QApplication.UnicodeUTF8))
    self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
    self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Counts ROI", None, QtGui.QApplication.UnicodeUTF8))
    self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Proton Charge", None, QtGui.QApplication.UnicodeUTF8))
    self.label_13.setText(QtGui.QApplication.translate("MainWindow", "αi-calc", None, QtGui.QApplication.UnicodeUTF8))
    self.label_15.setText(QtGui.QApplication.translate("MainWindow", "2Θ", None, QtGui.QApplication.UnicodeUTF8))
    self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Direct Pixel", None, QtGui.QApplication.UnicodeUTF8))
    self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Data Reduction", None, QtGui.QApplication.UnicodeUTF8))
    self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Normalization:", None, QtGui.QApplication.UnicodeUTF8))
    self.normalizationLabel.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
    self.selectedChannel.setItemText(0, QtGui.QApplication.translate("MainWindow", "x/+/++", None, QtGui.QApplication.UnicodeUTF8))
    self.selectedChannel.setItemText(1, QtGui.QApplication.translate("MainWindow", "-/--", None, QtGui.QApplication.UnicodeUTF8))
    self.selectedChannel.setItemText(2, QtGui.QApplication.translate("MainWindow", "+-", None, QtGui.QApplication.UnicodeUTF8))
    self.selectedChannel.setItemText(3, QtGui.QApplication.translate("MainWindow", "-+", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(0)
    item.setText(QtGui.QApplication.translate("MainWindow", "File No.", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "File Number", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(1)
    item.setText(QtGui.QApplication.translate("MainWindow", "I0", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "Scaling Factor", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(2)
    item.setText(QtGui.QApplication.translate("MainWindow", "P0", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "First Point", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(3)
    item.setText(QtGui.QApplication.translate("MainWindow", "PN", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "Last Point", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(4)
    item.setText(QtGui.QApplication.translate("MainWindow", "x0", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "X-Position of Window for Reflectivity", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(5)
    item.setText(QtGui.QApplication.translate("MainWindow", "xw", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "X-Width of Window for Reflectivity", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(6)
    item.setText(QtGui.QApplication.translate("MainWindow", "y0", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "Y-Position of Window for Reflectivity", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(7)
    item.setText(QtGui.QApplication.translate("MainWindow", "yw", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "Y-Width of Window for Reflectivity", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(8)
    item.setText(QtGui.QApplication.translate("MainWindow", "bg0", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "Background Region Center", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(9)
    item.setText(QtGui.QApplication.translate("MainWindow", "bgw", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "Background Region Width", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(10)
    item.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(11)
    item.setText(QtGui.QApplication.translate("MainWindow", "DP", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "DirectPixel", None, QtGui.QApplication.UnicodeUTF8))
    item = self.reductionTable.horizontalHeaderItem(12)
    item.setText(QtGui.QApplication.translate("MainWindow", "TTH", None, QtGui.QApplication.UnicodeUTF8))
    item.setToolTip(QtGui.QApplication.translate("MainWindow", "Two Theta of Detector Arm", None, QtGui.QApplication.UnicodeUTF8))
    self.reduceButton.setText(QtGui.QApplication.translate("MainWindow", "Reduce", None, QtGui.QApplication.UnicodeUTF8))
    self.plotTab.setTabText(self.plotTab.indexOf(self.Overview), QtGui.QApplication.translate("MainWindow", "Overview", None, QtGui.QApplication.UnicodeUTF8))
    self.plotTab.setTabText(self.plotTab.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "X-Y", None, QtGui.QApplication.UnicodeUTF8))
    self.plotTab.setTabText(self.plotTab.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "X-ToF", None, QtGui.QApplication.UnicodeUTF8))
    self.plotTab.setTabText(self.plotTab.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Off-Specular", None, QtGui.QApplication.UnicodeUTF8))
    self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
    self.menuReduce.setTitle(QtGui.QApplication.translate("MainWindow", "Reduce", None, QtGui.QApplication.UnicodeUTF8))
    self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
    self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PlotOptions", None, QtGui.QApplication.UnicodeUTF8))
    self.show_colorbars.setText(QtGui.QApplication.translate("MainWindow", "Show Colorbars", None, QtGui.QApplication.UnicodeUTF8))
    self.hide_plots.setText(QtGui.QApplication.translate("MainWindow", "Hide Nonexisting Channels", None, QtGui.QApplication.UnicodeUTF8))
    self.normalizeXTof.setText(QtGui.QApplication.translate("MainWindow", "Normalize X-ToF Map", None, QtGui.QApplication.UnicodeUTF8))
    self.color_selector.setItemText(0, QtGui.QApplication.translate("MainWindow", "gist_ncar", None, QtGui.QApplication.UnicodeUTF8))
    self.color_selector.setItemText(1, QtGui.QApplication.translate("MainWindow", "gist_rainbow", None, QtGui.QApplication.UnicodeUTF8))
    self.color_selector.setItemText(2, QtGui.QApplication.translate("MainWindow", "jet", None, QtGui.QApplication.UnicodeUTF8))
    self.color_selector.setItemText(3, QtGui.QApplication.translate("MainWindow", "hsv", None, QtGui.QApplication.UnicodeUTF8))
    self.color_selector.setItemText(4, QtGui.QApplication.translate("MainWindow", "hot", None, QtGui.QApplication.UnicodeUTF8))
    self.color_selector.setItemText(5, QtGui.QApplication.translate("MainWindow", "binary", None, QtGui.QApplication.UnicodeUTF8))
    self.dockWidget_3.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Y-Projection", None, QtGui.QApplication.UnicodeUTF8))
    self.dockWidget_4.setWindowTitle(QtGui.QApplication.translate("MainWindow", "X-Projection", None, QtGui.QApplication.UnicodeUTF8))
    self.xprojUseQuantiles.setText(QtGui.QApplication.translate("MainWindow", "Use Quantiles", None, QtGui.QApplication.UnicodeUTF8))
    self.label_16.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
    self.dockWidget_5.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Reflectivity", None, QtGui.QApplication.UnicodeUTF8))
    self.dockWidget_6.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Reflectivity Extraction", None, QtGui.QApplication.UnicodeUTF8))
    self.label_4.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
    self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
    self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Scale 10^", None, QtGui.QApplication.UnicodeUTF8))
    self.label_2.setText(QtGui.QApplication.translate("MainWindow", "width", None, QtGui.QApplication.UnicodeUTF8))
    self.label.setText(QtGui.QApplication.translate("MainWindow", "position", None, QtGui.QApplication.UnicodeUTF8))
    self.label_6.setText(QtGui.QApplication.translate("MainWindow", "BG X", None, QtGui.QApplication.UnicodeUTF8))
    self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Range", None, QtGui.QApplication.UnicodeUTF8))
    self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
    self.dockWidget_7.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Overwrite Parameters", None, QtGui.QApplication.UnicodeUTF8))
    self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Direct Pixel", None, QtGui.QApplication.UnicodeUTF8))
    self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Dangle0", None, QtGui.QApplication.UnicodeUTF8))
    self.dangle0Overwrite.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
    self.fanReflectivity.setText(QtGui.QApplication.translate("MainWindow", "Extract from \"Fan\"-Reflection", None, QtGui.QApplication.UnicodeUTF8))
    self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
    self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a new file (Ctrl+O)", None, QtGui.QApplication.UnicodeUTF8))
    self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
    self.actionNext_File.setText(QtGui.QApplication.translate("MainWindow", "Next File", None, QtGui.QApplication.UnicodeUTF8))
    self.actionNext_File.setToolTip(QtGui.QApplication.translate("MainWindow", "Next file in active folder (Ctrl+Down)", None, QtGui.QApplication.UnicodeUTF8))
    self.actionNext_File.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Down", None, QtGui.QApplication.UnicodeUTF8))
    self.actionPrevious_File.setText(QtGui.QApplication.translate("MainWindow", "Previous File", None, QtGui.QApplication.UnicodeUTF8))
    self.actionPrevious_File.setToolTip(QtGui.QApplication.translate("MainWindow", "Previous file in current foldet (Ctrl+Up)", None, QtGui.QApplication.UnicodeUTF8))
    self.actionPrevious_File.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Up", None, QtGui.QApplication.UnicodeUTF8))
    self.actionNorm.setText(QtGui.QApplication.translate("MainWindow", "Set Normalization", None, QtGui.QApplication.UnicodeUTF8))
    self.actionNorm.setToolTip(QtGui.QApplication.translate("MainWindow", "Take current dataset for normalization (Ctrl+N)", None, QtGui.QApplication.UnicodeUTF8))
    self.actionNorm.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAddPlot.setText(QtGui.QApplication.translate("MainWindow", "Keep Plot in List", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAddPlot.setToolTip(QtGui.QApplication.translate("MainWindow", "Add to current dataset to data reduction list (Ctrl+K)", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAddPlot.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))
    self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear List", None, QtGui.QApplication.UnicodeUTF8))
    self.actionClear.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove all plots from data reduction list", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAdjust_Dirct_Beam.setText(QtGui.QApplication.translate("MainWindow", "Adjust Dirct Beam", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAdjust_Dirct_Beam.setToolTip(QtGui.QApplication.translate("MainWindow", "Use active dataset to set overwrite parameters for direct pixel and Dangle0", None, QtGui.QApplication.UnicodeUTF8))
    self.actionNormalizeScaling.setText(QtGui.QApplication.translate("MainWindow", "Set Scaling", None, QtGui.QApplication.UnicodeUTF8))
    self.actionNormalizeScaling.setToolTip(QtGui.QApplication.translate("MainWindow", "Get normalization scale from total reflection", None, QtGui.QApplication.UnicodeUTF8))
    self.actionRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove Line", None, QtGui.QApplication.UnicodeUTF8))
    self.actionRemove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove one plots from data reduction list", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MPLWidget
from persistentframe import PersistentFrame
from . import icons_rc
