#-*- coding: utf-8 -*-
'''
  Templeates used for ASCII file creation.
'''


GP_TEMPLATE=u"""#!/usr/bin/gnuplot
# Gnuplot script automatically generated by QuickNXS.
# Can be used to create plots of exported datasets.
# 
set term pngcairo enhanced size 1600,1200 font "Sans,24" lw 2
set output "%(output)s"
set encoding utf8

set xlabel "%(xlabel)s"
set format y "10^{%%L}"
set ylabel "%(ylabel)s" offset -1
set title "%(title)s"

set log y

plot %(plot_lines)s
"""

GP_LINE=u'"%s" u 1:2:3 w errorlines t "(%s)" lw 1.5 pt 7'
GP_SEP=u',\\\n     '

FILE_HEADER=u'''# Datafile created by QuickNXS
# Type: %(datatype)s
# Input file indices: %(indices)s
# Extracted channels: %(channels)s
#
# Parameters used for extraction:
# I0           P0           PN           x0           xw           y0           yw           bg0          bgw          File
%(params_lines)s
#
# Column Units:
# %(column_units)s
# Column Names:
# %(column_names)s
'''
FILE_HEADER_PARAMS=u'%(scale)-12g %(P0)-12i %(PN)-12i %(x_pos)-12g %(x_width)-12g %(y_pos)-12g %(y_width)-12g %(bg_pos)-12g %(bg_width)-12g %(filename)-12s '

DICTIZE_CHANNELS={
                 'x': 'unpolarized',
                 '+': 'up',
                 '-': 'down',
                 '++': 'upup',
                 '--': 'downdown',
                 '+-': 'updown',
                 '-+': 'downup',
                 }
