; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EFFD5A67-5CA0-4473-B67F-FC7B867D5085}
AppName=QuickNXS
AppVersion=0.9
;AppVerName=QuickNXS 0.9
AppPublisher=Oak Ridge National Laboratory
AppPublisherURL=http://neutrons.ornl.gov/mr
AppSupportURL=http://neutrons.ornl.gov/mr
AppUpdatesURL=http://neutrons.ornl.gov/mr
DefaultDirName={pf}\QuickNXS
DefaultGroupName=QuickNXS
OutputBaseFilename=quicknxs_0.9_setup
Compression=lzma
SolidCompression=true
InternalCompressLevel=ultra

[Languages]
Name: english; MessagesFile: compiler:Default.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: ..\dist\quicknxs.exe; DestDir: {app}; Flags: ignoreversion
Source: ..\dist\*; DestDir: {app}; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: {group}\QuickNXS; Filename: {app}\quicknxs.exe
Name: {commondesktop}\QuickNXS; Filename: {app}\quicknxs.exe; Tasks: desktopicon

[Run]
Filename: {app}\quicknxs.exe; Description: {cm:LaunchProgram,QuickNXS}; Flags: nowait postinstall skipifsilent
