# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/background_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(490, 658)
    self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
    self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.splitter = QtWidgets.QSplitter(Dialog)
    self.splitter.setOrientation(QtCore.Qt.Vertical)
    self.splitter.setObjectName("splitter")
    self.xTof = MPLWidget(self.splitter)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(1)
    sizePolicy.setHeightForWidth(self.xTof.sizePolicy().hasHeightForWidth())
    self.xTof.setSizePolicy(sizePolicy)
    self.xTof.setObjectName("xTof")
    self.BG = MPLWidget(self.splitter)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(1)
    sizePolicy.setHeightForWidth(self.BG.sizePolicy().hasHeightForWidth())
    self.BG.setSizePolicy(sizePolicy)
    self.BG.setObjectName("BG")
    self.frame = QtWidgets.QFrame(self.splitter)
    self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame.setObjectName("frame")
    self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
    self.verticalLayout.setObjectName("verticalLayout")
    self.widget_2 = QtWidgets.QWidget(self.frame)
    self.widget_2.setObjectName("widget_2")
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
    self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.polyregionActive = QtWidgets.QCheckBox(self.widget_2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.polyregionActive.sizePolicy().hasHeightForWidth())
    self.polyregionActive.setSizePolicy(sizePolicy)
    self.polyregionActive.setObjectName("polyregionActive")
    self.horizontalLayout_2.addWidget(self.polyregionActive)
    self.polygonDisplay = QtWidgets.QLabel(self.widget_2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.polygonDisplay.sizePolicy().hasHeightForWidth())
    self.polygonDisplay.setSizePolicy(sizePolicy)
    self.polygonDisplay.setStyleSheet("color: rgb(192, 0, 0);")
    self.polygonDisplay.setText("")
    self.polygonDisplay.setObjectName("polygonDisplay")
    self.horizontalLayout_2.addWidget(self.polygonDisplay)
    self.addPoly = QtWidgets.QPushButton(self.widget_2)
    self.addPoly.setEnabled(False)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.addPoly.sizePolicy().hasHeightForWidth())
    self.addPoly.setSizePolicy(sizePolicy)
    self.addPoly.setObjectName("addPoly")
    self.horizontalLayout_2.addWidget(self.addPoly)
    self.delPoly = QtWidgets.QPushButton(self.widget_2)
    self.delPoly.setEnabled(False)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.delPoly.sizePolicy().hasHeightForWidth())
    self.delPoly.setSizePolicy(sizePolicy)
    self.delPoly.setObjectName("delPoly")
    self.horizontalLayout_2.addWidget(self.delPoly)
    self.clearPoly = QtWidgets.QPushButton(self.widget_2)
    self.clearPoly.setEnabled(False)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.clearPoly.sizePolicy().hasHeightForWidth())
    self.clearPoly.setSizePolicy(sizePolicy)
    self.clearPoly.setObjectName("clearPoly")
    self.horizontalLayout_2.addWidget(self.clearPoly)
    self.verticalLayout.addWidget(self.widget_2)
    self.polyTable = QtWidgets.QTableWidget(self.frame)
    self.polyTable.setEnabled(False)
    self.polyTable.setMinimumSize(QtCore.QSize(0, 50))
    self.polyTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
    self.polyTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    self.polyTable.setObjectName("polyTable")
    self.polyTable.setColumnCount(8)
    self.polyTable.setRowCount(0)
    item = QtWidgets.QTableWidgetItem()
    self.polyTable.setHorizontalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem()
    self.polyTable.setHorizontalHeaderItem(1, item)
    item = QtWidgets.QTableWidgetItem()
    self.polyTable.setHorizontalHeaderItem(2, item)
    item = QtWidgets.QTableWidgetItem()
    self.polyTable.setHorizontalHeaderItem(3, item)
    item = QtWidgets.QTableWidgetItem()
    self.polyTable.setHorizontalHeaderItem(4, item)
    item = QtWidgets.QTableWidgetItem()
    self.polyTable.setHorizontalHeaderItem(5, item)
    item = QtWidgets.QTableWidgetItem()
    self.polyTable.setHorizontalHeaderItem(6, item)
    item = QtWidgets.QTableWidgetItem()
    self.polyTable.setHorizontalHeaderItem(7, item)
    self.polyTable.horizontalHeader().setDefaultSectionSize(40)
    self.polyTable.horizontalHeader().setMinimumSectionSize(20)
    self.verticalLayout.addWidget(self.polyTable)
    self.widget = QtWidgets.QWidget(self.frame)
    self.widget.setObjectName("widget")
    self.gridLayout = QtWidgets.QGridLayout(self.widget)
    self.gridLayout.setContentsMargins(0, 0, 0, 0)
    self.gridLayout.setObjectName("gridLayout")
    self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_3.setObjectName("horizontalLayout_3")
    self.presumeIofLambda = QtWidgets.QCheckBox(self.widget)
    self.presumeIofLambda.setObjectName("presumeIofLambda")
    self.horizontalLayout_3.addWidget(self.presumeIofLambda)
    self.calcAutoBackground = QtWidgets.QPushButton(self.widget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.calcAutoBackground.sizePolicy().hasHeightForWidth())
    self.calcAutoBackground.setSizePolicy(sizePolicy)
    self.calcAutoBackground.setObjectName("calcAutoBackground")
    self.horizontalLayout_3.addWidget(self.calcAutoBackground)
    self.label = QtWidgets.QLabel(self.widget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
    self.label.setSizePolicy(sizePolicy)
    self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label.setObjectName("label")
    self.horizontalLayout_3.addWidget(self.label)
    self.scaleFactor = QtWidgets.QDoubleSpinBox(self.widget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.scaleFactor.sizePolicy().hasHeightForWidth())
    self.scaleFactor.setSizePolicy(sizePolicy)
    self.scaleFactor.setDecimals(4)
    self.scaleFactor.setMaximum(100.0)
    self.scaleFactor.setSingleStep(0.05)
    self.scaleFactor.setProperty("value", 1.0)
    self.scaleFactor.setObjectName("scaleFactor")
    self.horizontalLayout_3.addWidget(self.scaleFactor)
    self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
    self.verticalLayout.addWidget(self.widget)
    self.horizontalLayout.addWidget(self.splitter)

    self.retranslateUi(Dialog)
    self.polyregionActive.toggled['bool'].connect(self.polyTable.setEnabled)
    self.polyregionActive.toggled['bool'].connect(self.clearPoly.setEnabled)
    self.polyregionActive.toggled['bool'].connect(self.delPoly.setEnabled)
    self.polyregionActive.toggled['bool'].connect(self.addPoly.setEnabled)
    self.addPoly.pressed.connect(Dialog.addPolygon)
    self.presumeIofLambda.toggled['bool'].connect(Dialog.optionChanged)
    self.delPoly.pressed.connect(Dialog.delPolygon)
    self.clearPoly.pressed.connect(Dialog.clearPolygons)
    self.polyTable.itemChanged['QTableWidgetItem*'].connect(Dialog.polygonChanged)
    self.polyregionActive.toggled['bool'].connect(Dialog.optionChanged)
    self.polyregionActive.toggled['bool'].connect(Dialog.drawXTof)
    self.scaleFactor.valueChanged['double'].connect(Dialog.optionChanged)
    self.calcAutoBackground.pressed.connect(Dialog.calcAutoBackground)
    QtCore.QMetaObject.connectSlotsByName(Dialog)
    Dialog.setTabOrder(self.polyregionActive, self.addPoly)
    Dialog.setTabOrder(self.addPoly, self.delPoly)
    Dialog.setTabOrder(self.delPoly, self.clearPoly)
    Dialog.setTabOrder(self.clearPoly, self.polyTable)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "QuickNXS - Advanced Background"))
    self.polyregionActive.setText(_translate("Dialog", "Polygon regions"))
    self.addPoly.setText(_translate("Dialog", "Add"))
    self.delPoly.setText(_translate("Dialog", "Delete"))
    self.clearPoly.setText(_translate("Dialog", "Clear"))
    item = self.polyTable.horizontalHeaderItem(0)
    item.setText(_translate("Dialog", "λ1"))
    item = self.polyTable.horizontalHeaderItem(1)
    item.setText(_translate("Dialog", "x1"))
    item = self.polyTable.horizontalHeaderItem(2)
    item.setText(_translate("Dialog", "λ2"))
    item = self.polyTable.horizontalHeaderItem(3)
    item.setText(_translate("Dialog", "x2"))
    item = self.polyTable.horizontalHeaderItem(4)
    item.setText(_translate("Dialog", "λ3"))
    item = self.polyTable.horizontalHeaderItem(5)
    item.setText(_translate("Dialog", "x3"))
    item = self.polyTable.horizontalHeaderItem(6)
    item.setText(_translate("Dialog", "λ4"))
    item = self.polyTable.horizontalHeaderItem(7)
    item.setText(_translate("Dialog", "x4"))
    self.presumeIofLambda.setText(_translate("Dialog", "Presume BG~I(λ)"))
    self.calcAutoBackground.setText(_translate("Dialog", "Auto"))
    self.label.setText(_translate("Dialog", "Scale Backgound"))

from .mplwidget import MPLWidget
