# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/point_picker_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(803, 578)
    self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
    self.verticalLayout.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout.setObjectName("verticalLayout")
    self.splitter = QtWidgets.QSplitter(Dialog)
    self.splitter.setOrientation(QtCore.Qt.Horizontal)
    self.splitter.setObjectName("splitter")
    self.pointTable = QtWidgets.QTableWidget(self.splitter)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pointTable.sizePolicy().hasHeightForWidth())
    self.pointTable.setSizePolicy(sizePolicy)
    self.pointTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    self.pointTable.setProperty("showDropIndicator", False)
    self.pointTable.setAlternatingRowColors(True)
    self.pointTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
    self.pointTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    self.pointTable.setShowGrid(False)
    self.pointTable.setWordWrap(False)
    self.pointTable.setObjectName("pointTable")
    self.pointTable.setColumnCount(3)
    self.pointTable.setRowCount(2)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setVerticalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setVerticalHeaderItem(1, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setHorizontalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setHorizontalHeaderItem(1, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setHorizontalHeaderItem(2, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setItem(0, 0, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setItem(0, 1, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setItem(0, 2, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setItem(1, 0, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setItem(1, 1, item)
    item = QtWidgets.QTableWidgetItem()
    self.pointTable.setItem(1, 2, item)
    self.pointTable.horizontalHeader().setDefaultSectionSize(50)
    self.widget = QtWidgets.QWidget(self.splitter)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
    self.widget.setSizePolicy(sizePolicy)
    self.widget.setObjectName("widget")
    self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
    self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.frame = QtWidgets.QFrame(self.widget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
    self.frame.setSizePolicy(sizePolicy)
    self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame.setObjectName("frame")
    self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.plot = MPLWidget(self.frame)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
    self.plot.setSizePolicy(sizePolicy)
    self.plot.setObjectName("plot")
    self.verticalLayout_3.addWidget(self.plot)
    self.verticalLayout_2.addWidget(self.frame)
    self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
    self.buttonBox.setSizePolicy(sizePolicy)
    self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
    self.buttonBox.setObjectName("buttonBox")
    self.verticalLayout_2.addWidget(self.buttonBox)
    self.verticalLayout.addWidget(self.splitter)

    self.retranslateUi(Dialog)
    self.buttonBox.accepted.connect(Dialog.accept)
    self.buttonBox.rejected.connect(Dialog.reject)
    self.pointTable.itemSelectionChanged.connect(Dialog.selectionChanged)
    QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "Point Picker"))
    item = self.pointTable.verticalHeaderItem(0)
    item.setText(_translate("Dialog", "1"))
    item = self.pointTable.verticalHeaderItem(1)
    item.setText(_translate("Dialog", "2"))
    item = self.pointTable.horizontalHeaderItem(0)
    item.setText(_translate("Dialog", "αi"))
    item = self.pointTable.horizontalHeaderItem(1)
    item.setText(_translate("Dialog", "Qz"))
    item = self.pointTable.horizontalHeaderItem(2)
    item.setText(_translate("Dialog", "R"))
    __sortingEnabled = self.pointTable.isSortingEnabled()
    self.pointTable.setSortingEnabled(False)
    item = self.pointTable.item(0, 0)
    item.setText(_translate("Dialog", "0,5"))
    item = self.pointTable.item(0, 1)
    item.setText(_translate("Dialog", "0,05"))
    item = self.pointTable.item(0, 2)
    item.setText(_translate("Dialog", "10"))
    item = self.pointTable.item(1, 0)
    item.setText(_translate("Dialog", "1,"))
    item = self.pointTable.item(1, 1)
    item.setText(_translate("Dialog", "0,1"))
    item = self.pointTable.item(1, 2)
    item.setText(_translate("Dialog", "20"))
    self.pointTable.setSortingEnabled(__sortingEnabled)

from .mplwidget import MPLWidget
