# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/polarization_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(776, 710)
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.splitter_2 = QtWidgets.QSplitter(Dialog)
    self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
    self.splitter_2.setObjectName("splitter_2")
    self.splitter = QtWidgets.QSplitter(self.splitter_2)
    self.splitter.setOrientation(QtCore.Qt.Vertical)
    self.splitter.setObjectName("splitter")
    self.groupBox = QtWidgets.QGroupBox(self.splitter)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(10)
    sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
    self.groupBox.setSizePolicy(sizePolicy)
    self.groupBox.setObjectName("groupBox")
    self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
    self.verticalLayout.setObjectName("verticalLayout")
    self.flippingRatios = MPLWidget(self.groupBox)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(1)
    sizePolicy.setVerticalStretch(2)
    sizePolicy.setHeightForWidth(self.flippingRatios.sizePolicy().hasHeightForWidth())
    self.flippingRatios.setSizePolicy(sizePolicy)
    self.flippingRatios.setObjectName("flippingRatios")
    self.verticalLayout.addWidget(self.flippingRatios)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.label_2 = QtWidgets.QLabel(self.groupBox)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
    self.label_2.setSizePolicy(sizePolicy)
    self.label_2.setAlignment(QtCore.Qt.AlignCenter)
    self.label_2.setObjectName("label_2")
    self.horizontalLayout.addWidget(self.label_2)
    self.label_3 = QtWidgets.QLabel(self.groupBox)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
    self.label_3.setSizePolicy(sizePolicy)
    self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_3.setObjectName("label_3")
    self.horizontalLayout.addWidget(self.label_3)
    self.FR1 = QtWidgets.QLabel(self.groupBox)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FR1.sizePolicy().hasHeightForWidth())
    self.FR1.setSizePolicy(sizePolicy)
    self.FR1.setObjectName("FR1")
    self.horizontalLayout.addWidget(self.FR1)
    self.label_5 = QtWidgets.QLabel(self.groupBox)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
    self.label_5.setSizePolicy(sizePolicy)
    self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_5.setObjectName("label_5")
    self.horizontalLayout.addWidget(self.label_5)
    self.FR2 = QtWidgets.QLabel(self.groupBox)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FR2.sizePolicy().hasHeightForWidth())
    self.FR2.setSizePolicy(sizePolicy)
    self.FR2.setObjectName("FR2")
    self.horizontalLayout.addWidget(self.FR2)
    self.PolLabel = QtWidgets.QLabel(self.groupBox)
    self.PolLabel.setText("")
    self.PolLabel.setObjectName("PolLabel")
    self.horizontalLayout.addWidget(self.PolLabel)
    self.exportFRButton = QtWidgets.QPushButton(self.groupBox)
    self.exportFRButton.setObjectName("exportFRButton")
    self.horizontalLayout.addWidget(self.exportFRButton)
    self.verticalLayout.addLayout(self.horizontalLayout)
    self.groupBox1 = QtWidgets.QGroupBox(self.splitter)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(1)
    sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
    self.groupBox1.setSizePolicy(sizePolicy)
    self.groupBox1.setObjectName("groupBox1")
    self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox1)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_3.setObjectName("horizontalLayout_3")
    self.pushButton_2 = QtWidgets.QPushButton(self.groupBox1)
    self.pushButton_2.setObjectName("pushButton_2")
    self.horizontalLayout_3.addWidget(self.pushButton_2)
    self.pushButton = QtWidgets.QPushButton(self.groupBox1)
    self.pushButton.setObjectName("pushButton")
    self.horizontalLayout_3.addWidget(self.pushButton)
    self.pushButton_5 = QtWidgets.QPushButton(self.groupBox1)
    self.pushButton_5.setObjectName("pushButton_5")
    self.horizontalLayout_3.addWidget(self.pushButton_5)
    self.verticalLayout_2.addLayout(self.horizontalLayout_3)
    self.wlTable = QtWidgets.QTableWidget(self.groupBox1)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(1)
    sizePolicy.setHeightForWidth(self.wlTable.sizePolicy().hasHeightForWidth())
    self.wlTable.setSizePolicy(sizePolicy)
    self.wlTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
    self.wlTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    self.wlTable.setObjectName("wlTable")
    self.wlTable.setColumnCount(4)
    self.wlTable.setRowCount(0)
    item = QtWidgets.QTableWidgetItem()
    self.wlTable.setHorizontalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem()
    self.wlTable.setHorizontalHeaderItem(1, item)
    item = QtWidgets.QTableWidgetItem()
    self.wlTable.setHorizontalHeaderItem(2, item)
    item = QtWidgets.QTableWidgetItem()
    self.wlTable.setHorizontalHeaderItem(3, item)
    self.verticalLayout_2.addWidget(self.wlTable)
    self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_4.setObjectName("horizontalLayout_4")
    self.pushButton_4 = QtWidgets.QPushButton(self.groupBox1)
    self.pushButton_4.setObjectName("pushButton_4")
    self.horizontalLayout_4.addWidget(self.pushButton_4)
    self.pushButton_6 = QtWidgets.QPushButton(self.groupBox1)
    self.pushButton_6.setObjectName("pushButton_6")
    self.horizontalLayout_4.addWidget(self.pushButton_6)
    self.pushButton_3 = QtWidgets.QPushButton(self.groupBox1)
    self.pushButton_3.setObjectName("pushButton_3")
    self.horizontalLayout_4.addWidget(self.pushButton_3)
    self.verticalLayout_2.addLayout(self.horizontalLayout_4)
    self.xTable = QtWidgets.QTableWidget(self.groupBox1)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(1)
    sizePolicy.setHeightForWidth(self.xTable.sizePolicy().hasHeightForWidth())
    self.xTable.setSizePolicy(sizePolicy)
    self.xTable.setObjectName("xTable")
    self.xTable.setColumnCount(2)
    self.xTable.setRowCount(0)
    item = QtWidgets.QTableWidgetItem()
    self.xTable.setHorizontalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem()
    self.xTable.setHorizontalHeaderItem(1, item)
    self.verticalLayout_2.addWidget(self.xTable)
    self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_2)
    self.groupBox_2.setObjectName("groupBox_2")
    self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.splitter_3 = QtWidgets.QSplitter(self.groupBox_2)
    self.splitter_3.setOrientation(QtCore.Qt.Vertical)
    self.splitter_3.setObjectName("splitter_3")
    self.widget_2 = QtWidgets.QWidget(self.splitter_3)
    self.widget_2.setObjectName("widget_2")
    self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
    self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_5.setObjectName("verticalLayout_5")
    self.label = QtWidgets.QLabel(self.widget_2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
    self.label.setSizePolicy(sizePolicy)
    self.label.setAlignment(QtCore.Qt.AlignCenter)
    self.label.setObjectName("label")
    self.verticalLayout_5.addWidget(self.label)
    self.wavelengthPol = MPLWidget(self.widget_2)
    self.wavelengthPol.setObjectName("wavelengthPol")
    self.verticalLayout_5.addWidget(self.wavelengthPol)
    self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5.setObjectName("horizontalLayout_5")
    self.polErrorbars = QtWidgets.QCheckBox(self.widget_2)
    self.polErrorbars.setObjectName("polErrorbars")
    self.horizontalLayout_5.addWidget(self.polErrorbars)
    self.exportButton = QtWidgets.QPushButton(self.widget_2)
    self.exportButton.setEnabled(False)
    self.exportButton.setObjectName("exportButton")
    self.horizontalLayout_5.addWidget(self.exportButton)
    self.exportDetButton = QtWidgets.QPushButton(self.widget_2)
    self.exportDetButton.setEnabled(False)
    self.exportDetButton.setObjectName("exportDetButton")
    self.horizontalLayout_5.addWidget(self.exportDetButton)
    self.verticalLayout_5.addLayout(self.horizontalLayout_5)
    self.widget = QtWidgets.QWidget(self.splitter_3)
    self.widget.setObjectName("widget")
    self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
    self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_4.setObjectName("verticalLayout_4")
    self.label_4 = QtWidgets.QLabel(self.widget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
    self.label_4.setSizePolicy(sizePolicy)
    self.label_4.setAlignment(QtCore.Qt.AlignCenter)
    self.label_4.setObjectName("label_4")
    self.verticalLayout_4.addWidget(self.label_4)
    self.detectorPol = MPLWidget(self.widget)
    self.detectorPol.setObjectName("detectorPol")
    self.verticalLayout_4.addWidget(self.detectorPol)
    self.verticalLayout_3.addWidget(self.splitter_3)
    self.horizontalLayout_2.addWidget(self.splitter_2)

    self.retranslateUi(Dialog)
    self.pushButton_2.pressed.connect(Dialog.addWL)
    self.pushButton.pressed.connect(Dialog.clearWL)
    self.pushButton_4.pressed.connect(Dialog.addX)
    self.pushButton_3.pressed.connect(Dialog.clearX)
    self.wlTable.cellChanged['int','int'].connect(Dialog.update_fr)
    self.pushButton_5.pressed.connect(Dialog.assignFM)
    self.polErrorbars.toggled['bool'].connect(Dialog.update_fr)
    self.exportButton.pressed.connect(Dialog.exportPolarizationParameters)
    self.exportFRButton.clicked.connect(Dialog.exportFR)
    self.exportDetButton.clicked.connect(Dialog.exportFRDetector)
    self.pushButton_6.clicked.connect(Dialog.addXMultiple)
    QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "QuickNXS - Polarization"))
    self.groupBox.setTitle(_translate("Dialog", "Flipping Ratios (Current Run)"))
    self.label_2.setText(_translate("Dialog", "Mean:"))
    self.label_3.setText(_translate("Dialog", "SF1"))
    self.FR1.setText(_translate("Dialog", "0"))
    self.label_5.setText(_translate("Dialog", "SF2"))
    self.FR2.setText(_translate("Dialog", "0"))
    self.exportFRButton.setText(_translate("Dialog", "Export"))
    self.groupBox1.setTitle(_translate("Dialog", "Contributing Datasets"))
    self.pushButton_2.setText(_translate("Dialog", "Add"))
    self.pushButton.setText(_translate("Dialog", "Clear"))
    self.pushButton_5.setText(_translate("Dialog", "FM for Selection"))
    item = self.wlTable.horizontalHeaderItem(0)
    item.setText(_translate("Dialog", "Run No."))
    item = self.wlTable.horizontalHeaderItem(1)
    item.setText(_translate("Dialog", "λ-min"))
    item = self.wlTable.horizontalHeaderItem(2)
    item.setText(_translate("Dialog", "λ-max"))
    item = self.wlTable.horizontalHeaderItem(3)
    item.setText(_translate("Dialog", "FM Run"))
    self.pushButton_4.setText(_translate("Dialog", "Add"))
    self.pushButton_6.setText(_translate("Dialog", "Add Multiple..."))
    self.pushButton_3.setText(_translate("Dialog", "Clear"))
    item = self.xTable.horizontalHeaderItem(0)
    item.setText(_translate("Dialog", "Run No."))
    item = self.xTable.horizontalHeaderItem(1)
    item.setText(_translate("Dialog", "PixX"))
    self.groupBox_2.setTitle(_translate("Dialog", "Polarization Parameters"))
    self.label.setText(_translate("Dialog", "Wavelength Dependance"))
    self.polErrorbars.setText(_translate("Dialog", "Show Errorbars"))
    self.exportButton.setText(_translate("Dialog", "Export Parames."))
    self.exportDetButton.setText(_translate("Dialog", "Export Det."))
    self.label_4.setText(_translate("Dialog", "Detector Position Dependance"))

from .mplwidget import MPLWidget
