# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/quicklog_window.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName("MainWindow")
    MainWindow.resize(800, 600)
    icon = QtGui.QIcon.fromTheme("system-help")
    MainWindow.setWindowIcon(icon)
    self.centralwidget = QtWidgets.QWidget(MainWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
    self.verticalLayout.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout.setSpacing(1)
    self.verticalLayout.setObjectName("verticalLayout")
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.follow = QtWidgets.QCheckBox(self.centralwidget)
    self.follow.setChecked(True)
    self.follow.setObjectName("follow")
    self.horizontalLayout.addWidget(self.follow)
    self.label = QtWidgets.QLabel(self.centralwidget)
    self.label.setObjectName("label")
    self.horizontalLayout.addWidget(self.label)
    self.minSeverity = QtWidgets.QComboBox(self.centralwidget)
    self.minSeverity.setObjectName("minSeverity")
    self.minSeverity.addItem("")
    self.minSeverity.addItem("")
    self.minSeverity.addItem("")
    self.minSeverity.addItem("")
    self.minSeverity.addItem("")
    self.horizontalLayout.addWidget(self.minSeverity)
    self.filterThreadLabel = QtWidgets.QLabel(self.centralwidget)
    self.filterThreadLabel.setObjectName("filterThreadLabel")
    self.horizontalLayout.addWidget(self.filterThreadLabel)
    self.filterThread = QtWidgets.QComboBox(self.centralwidget)
    self.filterThread.setObjectName("filterThread")
    self.filterThread.addItem("")
    self.horizontalLayout.addWidget(self.filterThread)
    self.verticalLayout.addLayout(self.horizontalLayout)
    self.logTree = QtWidgets.QTreeWidget(self.centralwidget)
    self.logTree.setObjectName("logTree")
    self.verticalLayout.addWidget(self.logTree)
    MainWindow.setCentralWidget(self.centralwidget)
    self.menubar = QtWidgets.QMenuBar(MainWindow)
    self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
    self.menubar.setObjectName("menubar")
    self.menuFile = QtWidgets.QMenu(self.menubar)
    self.menuFile.setObjectName("menuFile")
    MainWindow.setMenuBar(self.menubar)
    self.actionOpen = QtWidgets.QAction(MainWindow)
    self.actionOpen.setObjectName("actionOpen")
    self.actionReload = QtWidgets.QAction(MainWindow)
    self.actionReload.setObjectName("actionReload")
    self.menuFile.addAction(self.actionOpen)
    self.menuFile.addAction(self.actionReload)
    self.menubar.addAction(self.menuFile.menuAction())

    self.retranslateUi(MainWindow)
    self.minSeverity.currentIndexChanged['int'].connect(MainWindow.updateLog)
    self.filterThread.currentIndexChanged['int'].connect(MainWindow.updateLog)
    self.actionOpen.triggered.connect(MainWindow.openFile)
    self.actionReload.triggered.connect(MainWindow.reloadFile)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    _translate = QtCore.QCoreApplication.translate
    MainWindow.setWindowTitle(_translate("MainWindow", "QuickLog"))
    self.follow.setText(_translate("MainWindow", "Follow"))
    self.label.setText(_translate("MainWindow", "Filter Severity Below"))
    self.minSeverity.setItemText(0, _translate("MainWindow", "DEBUG"))
    self.minSeverity.setItemText(1, _translate("MainWindow", "INFO"))
    self.minSeverity.setItemText(2, _translate("MainWindow", "WARNING"))
    self.minSeverity.setItemText(3, _translate("MainWindow", "ERROR"))
    self.minSeverity.setItemText(4, _translate("MainWindow", "FATAL"))
    self.filterThreadLabel.setText(_translate("MainWindow", "Filter Thread"))
    self.filterThread.setItemText(0, _translate("MainWindow", "All"))
    self.logTree.setSortingEnabled(True)
    self.logTree.headerItem().setText(0, _translate("MainWindow", "Severity"))
    self.logTree.headerItem().setText(1, _translate("MainWindow", "Time"))
    self.logTree.headerItem().setText(2, _translate("MainWindow", "Content"))
    self.logTree.headerItem().setText(3, _translate("MainWindow", "Source"))
    self.logTree.headerItem().setText(4, _translate("MainWindow", "Line"))
    self.logTree.headerItem().setText(5, _translate("MainWindow", "Method"))
    self.menuFile.setTitle(_translate("MainWindow", "File"))
    self.actionOpen.setText(_translate("MainWindow", "Open..."))
    self.actionReload.setText(_translate("MainWindow", "Reload"))
    self.actionReload.setShortcut(_translate("MainWindow", "F5"))

