# -*- coding: utf-8 -*-
#@PydevCodeAnalysisIgnore

# Form implementation generated from reading ui file 'designer/reduce_dialog.ui'
#
# Created: Tue Oct 22 17:34:57 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  def _fromUtf8(s):
    return s

try:
  _encoding = QtGui.QApplication.UnicodeUTF8
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
  def setupUi(self, Dialog):
    Dialog.setObjectName(_fromUtf8("Dialog"))
    Dialog.resize(400, 487)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/General/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    Dialog.setWindowIcon(icon)
    self.verticalLayout_4 = QtGui.QVBoxLayout(Dialog)
    self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
    self.tabWidget = QtGui.QTabWidget(Dialog)
    self.tabWidget.setDocumentMode(True)
    self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
    self.tab = QtGui.QWidget()
    self.tab.setObjectName(_fromUtf8("tab"))
    self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
    self.verticalLayout_2.setMargin(0)
    self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
    self.widget = QtGui.QWidget(self.tab)
    self.widget.setObjectName(_fromUtf8("widget"))
    self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
    self.horizontalLayout.setMargin(0)
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.groupBox_2 = QtGui.QGroupBox(self.widget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
    self.groupBox_2.setSizePolicy(sizePolicy)
    self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
    self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
    self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
    self.exportSpecular = QtGui.QCheckBox(self.groupBox_2)
    self.exportSpecular.setChecked(True)
    self.exportSpecular.setObjectName(_fromUtf8("exportSpecular"))
    self.verticalLayout.addWidget(self.exportSpecular)
    self.exportTrueSpecular = QtGui.QCheckBox(self.groupBox_2)
    self.exportTrueSpecular.setEnabled(False)
    self.exportTrueSpecular.setObjectName(_fromUtf8("exportTrueSpecular"))
    self.verticalLayout.addWidget(self.exportTrueSpecular)
    self.exportOffSpecular = QtGui.QCheckBox(self.groupBox_2)
    self.exportOffSpecular.setObjectName(_fromUtf8("exportOffSpecular"))
    self.verticalLayout.addWidget(self.exportOffSpecular)
    self.exportOffSpecularCorr = QtGui.QCheckBox(self.groupBox_2)
    self.exportOffSpecularCorr.setObjectName(_fromUtf8("exportOffSpecularCorr"))
    self.verticalLayout.addWidget(self.exportOffSpecularCorr)
    self.exportOffSpecularSmoothed = QtGui.QCheckBox(self.groupBox_2)
    self.exportOffSpecularSmoothed.setObjectName(_fromUtf8("exportOffSpecularSmoothed"))
    self.verticalLayout.addWidget(self.exportOffSpecularSmoothed)
    self.exportGISANS = QtGui.QCheckBox(self.groupBox_2)
    self.exportGISANS.setObjectName(_fromUtf8("exportGISANS"))
    self.verticalLayout.addWidget(self.exportGISANS)
    self.horizontalLayout.addWidget(self.groupBox_2)
    self.groupBox = QtGui.QGroupBox(self.widget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
    self.groupBox.setSizePolicy(sizePolicy)
    self.groupBox.setObjectName(_fromUtf8("groupBox"))
    self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
    self.verticalLayout_3.setSpacing(10)
    self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
    self.export_0 = QtGui.QCheckBox(self.groupBox)
    self.export_0.setChecked(True)
    self.export_0.setObjectName(_fromUtf8("export_0"))
    self.verticalLayout_3.addWidget(self.export_0)
    self.export_3 = QtGui.QCheckBox(self.groupBox)
    self.export_3.setChecked(True)
    self.export_3.setObjectName(_fromUtf8("export_3"))
    self.verticalLayout_3.addWidget(self.export_3)
    self.export_1 = QtGui.QCheckBox(self.groupBox)
    self.export_1.setChecked(True)
    self.export_1.setObjectName(_fromUtf8("export_1"))
    self.verticalLayout_3.addWidget(self.export_1)
    self.export_2 = QtGui.QCheckBox(self.groupBox)
    self.export_2.setChecked(True)
    self.export_2.setObjectName(_fromUtf8("export_2"))
    self.verticalLayout_3.addWidget(self.export_2)
    spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
    self.verticalLayout_3.addItem(spacerItem)
    self.horizontalLayout.addWidget(self.groupBox)
    self.verticalLayout_2.addWidget(self.widget)
    self.groupBox_3 = QtGui.QGroupBox(self.tab)
    self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
    self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.multiAscii = QtGui.QCheckBox(self.groupBox_3)
    self.multiAscii.setChecked(True)
    self.multiAscii.setObjectName(_fromUtf8("multiAscii"))
    self.gridLayout.addWidget(self.multiAscii, 0, 0, 1, 1)
    self.combinedAscii = QtGui.QCheckBox(self.groupBox_3)
    self.combinedAscii.setObjectName(_fromUtf8("combinedAscii"))
    self.gridLayout.addWidget(self.combinedAscii, 0, 1, 1, 1)
    self.matlab = QtGui.QCheckBox(self.groupBox_3)
    self.matlab.setObjectName(_fromUtf8("matlab"))
    self.gridLayout.addWidget(self.matlab, 1, 0, 1, 1)
    self.numpy = QtGui.QCheckBox(self.groupBox_3)
    self.numpy.setObjectName(_fromUtf8("numpy"))
    self.gridLayout.addWidget(self.numpy, 1, 1, 1, 1)
    self.gnuplot = QtGui.QCheckBox(self.groupBox_3)
    self.gnuplot.setObjectName(_fromUtf8("gnuplot"))
    self.gridLayout.addWidget(self.gnuplot, 2, 0, 1, 1)
    self.plot = QtGui.QCheckBox(self.groupBox_3)
    self.plot.setChecked(True)
    self.plot.setObjectName(_fromUtf8("plot"))
    self.gridLayout.addWidget(self.plot, 2, 1, 1, 1)
    self.genx = QtGui.QCheckBox(self.groupBox_3)
    self.genx.setObjectName(_fromUtf8("genx"))
    self.gridLayout.addWidget(self.genx, 3, 0, 1, 1)
    self.mantidplot = QtGui.QCheckBox(self.groupBox_3)
    self.mantidplot.setEnabled(False)
    self.mantidplot.setChecked(True)
    self.mantidplot.setObjectName(_fromUtf8("mantidplot"))
    self.gridLayout.addWidget(self.mantidplot, 3, 1, 1, 1)
    self.verticalLayout_2.addWidget(self.groupBox_3)
    self.horizontalLayout_4 = QtGui.QHBoxLayout()
    self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
    spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
    self.horizontalLayout_4.addItem(spacerItem1)
    self.label_7 = QtGui.QLabel(self.tab)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
    self.label_7.setSizePolicy(sizePolicy)
    self.label_7.setObjectName(_fromUtf8("label_7"))
    self.horizontalLayout_4.addWidget(self.label_7)
    self.sampleSize = QtGui.QDoubleSpinBox(self.tab)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.sampleSize.sizePolicy().hasHeightForWidth())
    self.sampleSize.setSizePolicy(sizePolicy)
    self.sampleSize.setDecimals(1)
    self.sampleSize.setProperty("value", 10.0)
    self.sampleSize.setObjectName(_fromUtf8("sampleSize"))
    self.horizontalLayout_4.addWidget(self.sampleSize)
    self.verticalLayout_2.addLayout(self.horizontalLayout_4)
    self.horizontalLayout_2 = QtGui.QHBoxLayout()
    self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
    self.label = QtGui.QLabel(self.tab)
    self.label.setObjectName(_fromUtf8("label"))
    self.horizontalLayout_2.addWidget(self.label)
    self.directoryEntry = QtGui.QLineEdit(self.tab)
    self.directoryEntry.setObjectName(_fromUtf8("directoryEntry"))
    self.horizontalLayout_2.addWidget(self.directoryEntry)
    self.toolButton = QtGui.QToolButton(self.tab)
    icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
    self.toolButton.setIcon(icon)
    self.toolButton.setObjectName(_fromUtf8("toolButton"))
    self.horizontalLayout_2.addWidget(self.toolButton)
    self.verticalLayout_2.addLayout(self.horizontalLayout_2)
    self.horizontalLayout_3 = QtGui.QHBoxLayout()
    self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
    self.label_2 = QtGui.QLabel(self.tab)
    self.label_2.setObjectName(_fromUtf8("label_2"))
    self.horizontalLayout_3.addWidget(self.label_2)
    self.fileNameEntry = QtGui.QLineEdit(self.tab)
    self.fileNameEntry.setObjectName(_fromUtf8("fileNameEntry"))
    self.horizontalLayout_3.addWidget(self.fileNameEntry)
    self.verticalLayout_2.addLayout(self.horizontalLayout_3)
    self.tabWidget.addTab(self.tab, _fromUtf8(""))
    self.tab_2 = QtGui.QWidget()
    self.tab_2.setObjectName(_fromUtf8("tab_2"))
    self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
    self.verticalLayout_5.setContentsMargins(0, 4, 0, 0)
    self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
    self.gridLayout_3 = QtGui.QGridLayout()
    self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
    self.emailZIPData = QtGui.QCheckBox(self.tab_2)
    self.emailZIPData.setChecked(True)
    self.emailZIPData.setObjectName(_fromUtf8("emailZIPData"))
    self.gridLayout_3.addWidget(self.emailZIPData, 0, 2, 1, 1)
    self.emailSendPlots = QtGui.QRadioButton(self.tab_2)
    self.emailSendPlots.setObjectName(_fromUtf8("emailSendPlots"))
    self.gridLayout_3.addWidget(self.emailSendPlots, 1, 1, 1, 1)
    self.emailSendAll = QtGui.QRadioButton(self.tab_2)
    self.emailSendAll.setChecked(True)
    self.emailSendAll.setObjectName(_fromUtf8("emailSendAll"))
    self.gridLayout_3.addWidget(self.emailSendAll, 1, 0, 1, 1)
    self.emailSend = QtGui.QCheckBox(self.tab_2)
    self.emailSend.setObjectName(_fromUtf8("emailSend"))
    self.gridLayout_3.addWidget(self.emailSend, 0, 0, 1, 2)
    self.emailSendData = QtGui.QRadioButton(self.tab_2)
    self.emailSendData.setObjectName(_fromUtf8("emailSendData"))
    self.gridLayout_3.addWidget(self.emailSendData, 1, 2, 1, 1)
    self.verticalLayout_5.addLayout(self.gridLayout_3)
    self.gridLayout_2 = QtGui.QGridLayout()
    self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
    self.label_4 = QtGui.QLabel(self.tab_2)
    self.label_4.setObjectName(_fromUtf8("label_4"))
    self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
    self.emailTo = QtGui.QLineEdit(self.tab_2)
    self.emailTo.setObjectName(_fromUtf8("emailTo"))
    self.gridLayout_2.addWidget(self.emailTo, 0, 1, 1, 1)
    self.label_5 = QtGui.QLabel(self.tab_2)
    self.label_5.setObjectName(_fromUtf8("label_5"))
    self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
    self.emailCc = QtGui.QLineEdit(self.tab_2)
    self.emailCc.setObjectName(_fromUtf8("emailCc"))
    self.gridLayout_2.addWidget(self.emailCc, 1, 1, 1, 1)
    self.label_3 = QtGui.QLabel(self.tab_2)
    self.label_3.setObjectName(_fromUtf8("label_3"))
    self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
    self.emailSubject = QtGui.QLineEdit(self.tab_2)
    self.emailSubject.setObjectName(_fromUtf8("emailSubject"))
    self.gridLayout_2.addWidget(self.emailSubject, 2, 1, 1, 1)
    self.verticalLayout_5.addLayout(self.gridLayout_2)
    self.label_6 = QtGui.QLabel(self.tab_2)
    self.label_6.setObjectName(_fromUtf8("label_6"))
    self.verticalLayout_5.addWidget(self.label_6)
    self.emailText = QtGui.QPlainTextEdit(self.tab_2)
    self.emailText.setObjectName(_fromUtf8("emailText"))
    self.verticalLayout_5.addWidget(self.emailText)
    self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
    self.verticalLayout_4.addWidget(self.tabWidget)
    self.buttonBox = QtGui.QDialogButtonBox(Dialog)
    self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
    self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
    self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
    self.verticalLayout_4.addWidget(self.buttonBox)

    self.retranslateUi(Dialog)
    self.tabWidget.setCurrentIndex(0)
    QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
    QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
    QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.changeDir)
    QtCore.QObject.connect(self.gnuplot, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.multiAscii.setDisabled)
    QtCore.QMetaObject.connectSlotsByName(Dialog)
    Dialog.setTabOrder(self.directoryEntry, self.fileNameEntry)
    Dialog.setTabOrder(self.fileNameEntry, self.buttonBox)
    Dialog.setTabOrder(self.buttonBox, self.exportSpecular)
    Dialog.setTabOrder(self.exportSpecular, self.exportOffSpecular)
    Dialog.setTabOrder(self.exportOffSpecular, self.exportOffSpecularCorr)
    Dialog.setTabOrder(self.exportOffSpecularCorr, self.exportOffSpecularSmoothed)
    Dialog.setTabOrder(self.exportOffSpecularSmoothed, self.exportGISANS)
    Dialog.setTabOrder(self.exportGISANS, self.export_0)
    Dialog.setTabOrder(self.export_0, self.export_3)
    Dialog.setTabOrder(self.export_3, self.export_1)
    Dialog.setTabOrder(self.export_1, self.export_2)
    Dialog.setTabOrder(self.export_2, self.multiAscii)
    Dialog.setTabOrder(self.multiAscii, self.combinedAscii)
    Dialog.setTabOrder(self.combinedAscii, self.matlab)
    Dialog.setTabOrder(self.matlab, self.numpy)
    Dialog.setTabOrder(self.numpy, self.gnuplot)
    Dialog.setTabOrder(self.gnuplot, self.plot)
    Dialog.setTabOrder(self.plot, self.genx)
    Dialog.setTabOrder(self.genx, self.toolButton)
    Dialog.setTabOrder(self.toolButton, self.tabWidget)
    Dialog.setTabOrder(self.tabWidget, self.emailSend)
    Dialog.setTabOrder(self.emailSend, self.emailZIPData)
    Dialog.setTabOrder(self.emailZIPData, self.emailSendAll)
    Dialog.setTabOrder(self.emailSendAll, self.emailSendPlots)
    Dialog.setTabOrder(self.emailSendPlots, self.emailSendData)
    Dialog.setTabOrder(self.emailSendData, self.emailTo)
    Dialog.setTabOrder(self.emailTo, self.emailCc)
    Dialog.setTabOrder(self.emailCc, self.emailSubject)
    Dialog.setTabOrder(self.emailSubject, self.emailText)

  def retranslateUi(self, Dialog):
    Dialog.setWindowTitle(_translate("Dialog", "Reduction Options", None))
    self.groupBox_2.setTitle(_translate("Dialog", "Items", None))
    self.exportSpecular.setText(_translate("Dialog", "Specular", None))
    self.exportTrueSpecular.setText(_translate("Dialog", "True Specular", None))
    self.exportOffSpecular.setText(_translate("Dialog", "Off-Specular Raw", None))
    self.exportOffSpecularCorr.setText(_translate("Dialog", "Off-Specular Corrected", None))
    self.exportOffSpecularSmoothed.setText(_translate("Dialog", "Off-Specular Smoothed", None))
    self.exportGISANS.setText(_translate("Dialog", "GISANS", None))
    self.groupBox.setTitle(_translate("Dialog", "States to Extract", None))
    self.export_0.setText(_translate("Dialog", " X / + / ++/0V", None))
    self.export_3.setText(_translate("Dialog", "- / --/+V", None))
    self.export_1.setText(_translate("Dialog", "+-/-V", None))
    self.export_2.setText(_translate("Dialog", "-+", None))
    self.groupBox_3.setTitle(_translate("Dialog", "Output Formats", None))
    self.multiAscii.setText(_translate("Dialog", "ASCII for each channel", None))
    self.combinedAscii.setText(_translate("Dialog", "Combined ASCII", None))
    self.matlab.setText(_translate("Dialog", "Matlab", None))
    self.numpy.setText(_translate("Dialog", "Numpy .npz", None))
    self.gnuplot.setText(_translate("Dialog", "Gnuplot Script", None))
    self.plot.setText(_translate("Dialog", "Show Plot", None))
    self.genx.setText(_translate("Dialog", "GenX", None))
    self.mantidplot.setText(_translate("Dialog", "Push to Mantidplot", None))
    self.label_7.setText(_translate("Dialog", "Sample Size", None))
    self.sampleSize.setSuffix(_translate("Dialog", "mm", None))
    self.label.setText(_translate("Dialog", "Directory", None))
    self.toolButton.setText(_translate("Dialog", "...", None))
    self.label_2.setText(_translate("Dialog", "File Naming", None))
    self.fileNameEntry.setText(_translate("Dialog", "REF_M_{numbers}_{item}_{state}.{type}", None))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Output Options", None))
    self.emailZIPData.setText(_translate("Dialog", "ZIP Files", None))
    self.emailSendPlots.setText(_translate("Dialog", "Only Plots", None))
    self.emailSendAll.setText(_translate("Dialog", "All", None))
    self.emailSend.setText(_translate("Dialog", "Send email with result files", None))
    self.emailSendData.setText(_translate("Dialog", "Only Data", None))
    self.label_4.setText(_translate("Dialog", "To:", None))
    self.emailTo.setText(_translate("Dialog", "agf@ornl.gov", None))
    self.label_5.setText(_translate("Dialog", "CC:", None))
    self.label_3.setText(_translate("Dialog", "Subject:", None))
    self.label_6.setText(_translate("Dialog", "Message Text:", None))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Email Results", None))

from . import icons_rc
