# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/smooth_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(781, 608)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(":/General/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    Dialog.setWindowIcon(icon)
    self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.label = QtWidgets.QLabel(Dialog)
    self.label.setAlignment(QtCore.Qt.AlignCenter)
    self.label.setObjectName("label")
    self.verticalLayout.addWidget(self.label)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.kizmkfzVSqz = QtWidgets.QRadioButton(Dialog)
    self.kizmkfzVSqz.setChecked(True)
    self.kizmkfzVSqz.setObjectName("kizmkfzVSqz")
    self.horizontalLayout.addWidget(self.kizmkfzVSqz)
    self.qxVSqz = QtWidgets.QRadioButton(Dialog)
    self.qxVSqz.setObjectName("qxVSqz")
    self.horizontalLayout.addWidget(self.qxVSqz)
    self.kizVSkfz = QtWidgets.QRadioButton(Dialog)
    self.kizVSkfz.setObjectName("kizVSkfz")
    self.horizontalLayout.addWidget(self.kizVSkfz)
    self.verticalLayout.addLayout(self.horizontalLayout)
    self.plot = MPLWidget(Dialog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
    self.plot.setSizePolicy(sizePolicy)
    self.plot.setObjectName("plot")
    self.verticalLayout.addWidget(self.plot)
    self.horizontalLayout_2.addLayout(self.verticalLayout)
    self.widget = QtWidgets.QWidget(Dialog)
    self.widget.setObjectName("widget")
    self.gridLayout = QtWidgets.QGridLayout(self.widget)
    self.gridLayout.setContentsMargins(0, 0, 0, 0)
    self.gridLayout.setObjectName("gridLayout")
    self.gridXmax = QtWidgets.QDoubleSpinBox(self.widget)
    self.gridXmax.setDecimals(6)
    self.gridXmax.setMinimum(-1.0)
    self.gridXmax.setMaximum(1.0)
    self.gridXmax.setSingleStep(0.001)
    self.gridXmax.setProperty("value", 0.01)
    self.gridXmax.setObjectName("gridXmax")
    self.gridLayout.addWidget(self.gridXmax, 2, 3, 1, 1)
    self.sigmasCoupled = QtWidgets.QToolButton(self.widget)
    icon = QtGui.QIcon.fromTheme("system-lock-screen")
    self.sigmasCoupled.setIcon(icon)
    self.sigmasCoupled.setCheckable(True)
    self.sigmasCoupled.setChecked(True)
    self.sigmasCoupled.setObjectName("sigmasCoupled")
    self.gridLayout.addWidget(self.sigmasCoupled, 12, 0, 1, 1)
    spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
    self.gridLayout.addItem(spacerItem, 5, 3, 1, 1)
    self.sigmaY = QtWidgets.QDoubleSpinBox(self.widget)
    self.sigmaY.setEnabled(False)
    self.sigmaY.setDecimals(6)
    self.sigmaY.setMinimum(1e-06)
    self.sigmaY.setMaximum(1.0)
    self.sigmaY.setSingleStep(0.00025)
    self.sigmaY.setProperty("value", 0.0005)
    self.sigmaY.setObjectName("sigmaY")
    self.gridLayout.addWidget(self.sigmaY, 12, 3, 1, 1)
    self.label_12 = QtWidgets.QLabel(self.widget)
    self.label_12.setObjectName("label_12")
    self.gridLayout.addWidget(self.label_12, 4, 2, 1, 1)
    self.label_10 = QtWidgets.QLabel(self.widget)
    self.label_10.setObjectName("label_10")
    self.gridLayout.addWidget(self.label_10, 2, 2, 1, 1)
    self.label_2 = QtWidgets.QLabel(self.widget)
    self.label_2.setObjectName("label_2")
    self.gridLayout.addWidget(self.label_2, 10, 0, 1, 1)
    self.label_11 = QtWidgets.QLabel(self.widget)
    self.label_11.setObjectName("label_11")
    self.gridLayout.addWidget(self.label_11, 3, 2, 1, 1)
    spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
    self.gridLayout.addItem(spacerItem1, 13, 3, 1, 1)
    self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
    self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
    self.buttonBox.setObjectName("buttonBox")
    self.gridLayout.addWidget(self.buttonBox, 16, 0, 1, 4)
    self.label_8 = QtWidgets.QLabel(self.widget)
    self.label_8.setObjectName("label_8")
    self.gridLayout.addWidget(self.label_8, 12, 2, 1, 1)
    self.label_5 = QtWidgets.QLabel(self.widget)
    self.label_5.setObjectName("label_5")
    self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
    self.label_7 = QtWidgets.QLabel(self.widget)
    self.label_7.setObjectName("label_7")
    self.gridLayout.addWidget(self.label_7, 10, 2, 1, 1)
    self.gridYmin = QtWidgets.QDoubleSpinBox(self.widget)
    self.gridYmin.setDecimals(6)
    self.gridYmin.setMinimum(-1.0)
    self.gridYmin.setMaximum(1.0)
    self.gridYmin.setSingleStep(0.001)
    self.gridYmin.setObjectName("gridYmin")
    self.gridLayout.addWidget(self.gridYmin, 3, 3, 1, 1)
    spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
    self.gridLayout.addItem(spacerItem2, 9, 3, 1, 1)
    self.label_13 = QtWidgets.QLabel(self.widget)
    self.label_13.setAlignment(QtCore.Qt.AlignCenter)
    self.label_13.setObjectName("label_13")
    self.gridLayout.addWidget(self.label_13, 0, 0, 1, 4)
    self.label_9 = QtWidgets.QLabel(self.widget)
    self.label_9.setObjectName("label_9")
    self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
    self.gridYmax = QtWidgets.QDoubleSpinBox(self.widget)
    self.gridYmax.setDecimals(6)
    self.gridYmax.setMinimum(-1.0)
    self.gridYmax.setMaximum(1.0)
    self.gridYmax.setSingleStep(0.001)
    self.gridYmax.setProperty("value", 0.025)
    self.gridYmax.setObjectName("gridYmax")
    self.gridLayout.addWidget(self.gridYmax, 4, 3, 1, 1)
    self.gridSizeCoupled = QtWidgets.QToolButton(self.widget)
    icon = QtGui.QIcon.fromTheme("system-lock-screen")
    self.gridSizeCoupled.setIcon(icon)
    self.gridSizeCoupled.setCheckable(True)
    self.gridSizeCoupled.setChecked(True)
    self.gridSizeCoupled.setObjectName("gridSizeCoupled")
    self.gridLayout.addWidget(self.gridSizeCoupled, 8, 0, 1, 1)
    self.label_3 = QtWidgets.QLabel(self.widget)
    self.label_3.setObjectName("label_3")
    self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
    self.label_4 = QtWidgets.QLabel(self.widget)
    self.label_4.setObjectName("label_4")
    self.gridLayout.addWidget(self.label_4, 8, 2, 1, 1)
    self.gridSizeX = QtWidgets.QSpinBox(self.widget)
    self.gridSizeX.setEnabled(False)
    self.gridSizeX.setMinimum(10)
    self.gridSizeX.setMaximum(1000)
    self.gridSizeX.setSingleStep(10)
    self.gridSizeX.setProperty("value", 200)
    self.gridSizeX.setObjectName("gridSizeX")
    self.gridLayout.addWidget(self.gridSizeX, 6, 3, 1, 1)
    self.gridXmin = QtWidgets.QDoubleSpinBox(self.widget)
    self.gridXmin.setDecimals(6)
    self.gridXmin.setMinimum(-1.0)
    self.gridXmin.setMaximum(1.0)
    self.gridXmin.setSingleStep(0.001)
    self.gridXmin.setProperty("value", -0.01)
    self.gridXmin.setObjectName("gridXmin")
    self.gridLayout.addWidget(self.gridXmin, 1, 3, 1, 1)
    self.label_6 = QtWidgets.QLabel(self.widget)
    self.label_6.setObjectName("label_6")
    self.gridLayout.addWidget(self.label_6, 6, 2, 1, 1)
    self.sigmaX = QtWidgets.QDoubleSpinBox(self.widget)
    self.sigmaX.setDecimals(6)
    self.sigmaX.setMinimum(1e-06)
    self.sigmaX.setMaximum(1.0)
    self.sigmaX.setSingleStep(0.00025)
    self.sigmaX.setProperty("value", 0.0005)
    self.sigmaX.setObjectName("sigmaX")
    self.gridLayout.addWidget(self.sigmaX, 10, 3, 1, 1)
    spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout.addItem(spacerItem3, 15, 3, 1, 1)
    self.gridSizeY = QtWidgets.QSpinBox(self.widget)
    self.gridSizeY.setEnabled(False)
    self.gridSizeY.setMinimum(10)
    self.gridSizeY.setMaximum(1000)
    self.gridSizeY.setSingleStep(10)
    self.gridSizeY.setProperty("value", 200)
    self.gridSizeY.setObjectName("gridSizeY")
    self.gridLayout.addWidget(self.gridSizeY, 8, 3, 1, 1)
    self.label_14 = QtWidgets.QLabel(self.widget)
    self.label_14.setObjectName("label_14")
    self.gridLayout.addWidget(self.label_14, 14, 0, 1, 1)
    self.rSigmas = QtWidgets.QDoubleSpinBox(self.widget)
    self.rSigmas.setMinimum(1.0)
    self.rSigmas.setMaximum(10.0)
    self.rSigmas.setProperty("value", 3.0)
    self.rSigmas.setObjectName("rSigmas")
    self.gridLayout.addWidget(self.rSigmas, 14, 3, 1, 1)
    self.horizontalLayout_2.addWidget(self.widget)
    self.verticalLayout_2.addLayout(self.horizontalLayout_2)

    self.retranslateUi(Dialog)
    self.kizmkfzVSqz.clicked.connect(Dialog.drawPlot)
    self.kizVSkfz.clicked.connect(Dialog.drawPlot)
    self.qxVSqz.clicked.connect(Dialog.drawPlot)
    self.gridSizeCoupled.clicked['bool'].connect(self.gridSizeY.setDisabled)
    self.sigmasCoupled.clicked['bool'].connect(self.sigmaY.setDisabled)
    self.buttonBox.accepted.connect(Dialog.accept)
    self.buttonBox.rejected.connect(Dialog.reject)
    self.gridXmin.valueChanged['double'].connect(Dialog.updateSettings)
    self.gridXmax.valueChanged['double'].connect(Dialog.updateSettings)
    self.gridYmin.valueChanged['double'].connect(Dialog.updateSettings)
    self.gridYmax.valueChanged['double'].connect(Dialog.updateSettings)
    self.sigmaX.valueChanged['double'].connect(Dialog.updateSettings)
    self.sigmaY.valueChanged['double'].connect(Dialog.updateSettings)
    self.gridSizeCoupled.clicked.connect(Dialog.updateGrid)
    self.sigmasCoupled.clicked.connect(Dialog.updateSettings)
    self.gridSizeCoupled.clicked['bool'].connect(self.gridSizeX.setDisabled)
    QtCore.QMetaObject.connectSlotsByName(Dialog)
    Dialog.setTabOrder(self.gridXmin, self.gridXmax)
    Dialog.setTabOrder(self.gridXmax, self.gridYmin)
    Dialog.setTabOrder(self.gridYmin, self.gridYmax)
    Dialog.setTabOrder(self.gridYmax, self.gridSizeX)
    Dialog.setTabOrder(self.gridSizeX, self.gridSizeY)
    Dialog.setTabOrder(self.gridSizeY, self.sigmaX)
    Dialog.setTabOrder(self.sigmaX, self.sigmaY)
    Dialog.setTabOrder(self.sigmaY, self.rSigmas)
    Dialog.setTabOrder(self.rSigmas, self.buttonBox)
    Dialog.setTabOrder(self.buttonBox, self.kizmkfzVSqz)
    Dialog.setTabOrder(self.kizmkfzVSqz, self.qxVSqz)
    Dialog.setTabOrder(self.qxVSqz, self.kizVSkfz)
    Dialog.setTabOrder(self.kizVSkfz, self.gridSizeCoupled)
    Dialog.setTabOrder(self.gridSizeCoupled, self.sigmasCoupled)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "QuickNXS - Smooth Off-Specular"))
    self.label.setText(_translate("Dialog", "Off-Specular Preview"))
    self.kizmkfzVSqz.setText(_translate("Dialog", "(ki_z-kf_z) VS. Qz"))
    self.qxVSqz.setText(_translate("Dialog", "Qx VS. Qz"))
    self.kizVSkfz.setText(_translate("Dialog", "ki_z VS. kf_z"))
    self.label_12.setText(_translate("Dialog", "Y2"))
    self.label_10.setText(_translate("Dialog", "X2"))
    self.label_2.setText(_translate("Dialog", "Sigma"))
    self.label_11.setText(_translate("Dialog", "Y1"))
    self.label_8.setText(_translate("Dialog", "Y"))
    self.label_5.setText(_translate("Dialog", "Grid Region"))
    self.label_7.setText(_translate("Dialog", "X"))
    self.label_13.setText(_translate("Dialog", "Smoothing Parameters"))
    self.label_9.setText(_translate("Dialog", "X1"))
    self.label_3.setText(_translate("Dialog", "Grid Size"))
    self.label_4.setText(_translate("Dialog", "Y"))
    self.label_6.setText(_translate("Dialog", "X"))
    self.label_14.setText(_translate("Dialog", "R [Sigmas]"))

from .mplwidget import MPLWidget
from . import icons_rc
